name: seatd_display
description: Seatd display application skeleton.
publish_to: none
version: 0.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.5.0
  seatd_client:
    path: ../../packages/dart-seatd-client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
