// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: analytics.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveServicePeriod = `-- name: ArchiveServicePeriod :one
UPDATE service_periods
SET is_active = false,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND version = $4
RETURNING id, organisation_id, location_id, name, days_of_week, start_time, end_time, is_active, version, created_at, updated_at
`

type ArchiveServicePeriodParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	Version        int32     `json:"version"`
}

func (q *Queries) ArchiveServicePeriod(ctx context.Context, arg ArchiveServicePeriodParams) (ServicePeriod, error) {
	row := q.db.QueryRow(ctx, archiveServicePeriod,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.Version,
	)
	var i ServicePeriod
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.Name,
		&i.DaysOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServicePeriod = `-- name: CreateServicePeriod :one
INSERT INTO service_periods (
    organisation_id,
    location_id,
    name,
    days_of_week,
    start_time,
    end_time
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organisation_id, location_id, name, days_of_week, start_time, end_time, is_active, version, created_at, updated_at
`

type CreateServicePeriodParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	Name           string      `json:"name"`
	DaysOfWeek     []int16     `json:"days_of_week"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
}

func (q *Queries) CreateServicePeriod(ctx context.Context, arg CreateServicePeriodParams) (ServicePeriod, error) {
	row := q.db.QueryRow(ctx, createServicePeriod,
		arg.OrganisationID,
		arg.LocationID,
		arg.Name,
		arg.DaysOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i ServicePeriod
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.Name,
		&i.DaysOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnalyticsProjectorCheckpoint = `-- name: GetAnalyticsProjectorCheckpoint :one
SELECT projector_name, projector_version, cursor_occurred_at, cursor_event_id, lag_seconds, rebuild_status, rebuild_started_at, rebuild_completed_at, updated_at
FROM analytics_projector_checkpoints
WHERE projector_name = $1
`

func (q *Queries) GetAnalyticsProjectorCheckpoint(ctx context.Context, projectorName string) (AnalyticsProjectorCheckpoint, error) {
	row := q.db.QueryRow(ctx, getAnalyticsProjectorCheckpoint, projectorName)
	var i AnalyticsProjectorCheckpoint
	err := row.Scan(
		&i.ProjectorName,
		&i.ProjectorVersion,
		&i.CursorOccurredAt,
		&i.CursorEventID,
		&i.LagSeconds,
		&i.RebuildStatus,
		&i.RebuildStartedAt,
		&i.RebuildCompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyLocationMetric = `-- name: GetDailyLocationMetric :one
SELECT organisation_id, location_id, metric_date, bucket_start, bucket_end, active_table_count, occupancy_seconds, utilisation_basis_seconds, utilisation_rate, completed_session_count, turnover_rate, avg_session_seconds, p50_session_seconds, p90_session_seconds, assist_request_count, avg_assist_response_seconds, avg_assist_resolution_seconds, anomaly_count, projected_at
FROM analytics_daily_location_metrics
WHERE organisation_id = $1
  AND location_id = $2
  AND metric_date = $3
`

type GetDailyLocationMetricParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	MetricDate     pgtype.Date `json:"metric_date"`
}

func (q *Queries) GetDailyLocationMetric(ctx context.Context, arg GetDailyLocationMetricParams) (AnalyticsDailyLocationMetric, error) {
	row := q.db.QueryRow(ctx, getDailyLocationMetric, arg.OrganisationID, arg.LocationID, arg.MetricDate)
	var i AnalyticsDailyLocationMetric
	err := row.Scan(
		&i.OrganisationID,
		&i.LocationID,
		&i.MetricDate,
		&i.BucketStart,
		&i.BucketEnd,
		&i.ActiveTableCount,
		&i.OccupancySeconds,
		&i.UtilisationBasisSeconds,
		&i.UtilisationRate,
		&i.CompletedSessionCount,
		&i.TurnoverRate,
		&i.AvgSessionSeconds,
		&i.P50SessionSeconds,
		&i.P90SessionSeconds,
		&i.AssistRequestCount,
		&i.AvgAssistResponseSeconds,
		&i.AvgAssistResolutionSeconds,
		&i.AnomalyCount,
		&i.ProjectedAt,
	)
	return i, err
}

const listActiveServicePeriodsByLocation = `-- name: ListActiveServicePeriodsByLocation :many
SELECT id, organisation_id, location_id, name, days_of_week, start_time, end_time, is_active, version, created_at, updated_at
FROM service_periods
WHERE organisation_id = $1
  AND location_id = $2
  AND is_active
ORDER BY name
`

type ListActiveServicePeriodsByLocationParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

func (q *Queries) ListActiveServicePeriodsByLocation(ctx context.Context, arg ListActiveServicePeriodsByLocationParams) ([]ServicePeriod, error) {
	rows, err := q.db.Query(ctx, listActiveServicePeriodsByLocation, arg.OrganisationID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServicePeriod{}
	for rows.Next() {
		var i ServicePeriod
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.Name,
			&i.DaysOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyFloorMetrics = `-- name: ListDailyFloorMetrics :many
SELECT m.organisation_id, m.location_id, m.floor_id, m.metric_date, m.bucket_start, m.bucket_end, m.active_table_count, m.occupancy_seconds, m.utilisation_basis_seconds, m.utilisation_rate, m.completed_session_count, m.turnover_rate, m.avg_session_seconds, m.p50_session_seconds, m.p90_session_seconds, m.assist_request_count, m.avg_assist_response_seconds, m.avg_assist_resolution_seconds, m.anomaly_count, m.projected_at, f.name AS group_name
FROM analytics_daily_floor_metrics m
JOIN floors f ON f.id = m.floor_id
WHERE m.organisation_id = $1
  AND m.location_id = $2
  AND m.metric_date >= $3
  AND m.metric_date < $4
ORDER BY f.sort_order, f.name, m.metric_date
`

type ListDailyFloorMetricsParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	MetricDate     pgtype.Date `json:"metric_date"`
	MetricDate_2   pgtype.Date `json:"metric_date_2"`
}

type ListDailyFloorMetricsRow struct {
	OrganisationID             uuid.UUID          `json:"organisation_id"`
	LocationID                 uuid.UUID          `json:"location_id"`
	FloorID                    uuid.UUID          `json:"floor_id"`
	MetricDate                 pgtype.Date        `json:"metric_date"`
	BucketStart                pgtype.Timestamptz `json:"bucket_start"`
	BucketEnd                  pgtype.Timestamptz `json:"bucket_end"`
	ActiveTableCount           int32              `json:"active_table_count"`
	OccupancySeconds           float64            `json:"occupancy_seconds"`
	UtilisationBasisSeconds    float64            `json:"utilisation_basis_seconds"`
	UtilisationRate            float64            `json:"utilisation_rate"`
	CompletedSessionCount      int32              `json:"completed_session_count"`
	TurnoverRate               float64            `json:"turnover_rate"`
	AvgSessionSeconds          float64            `json:"avg_session_seconds"`
	P50SessionSeconds          float64            `json:"p50_session_seconds"`
	P90SessionSeconds          float64            `json:"p90_session_seconds"`
	AssistRequestCount         int32              `json:"assist_request_count"`
	AvgAssistResponseSeconds   float64            `json:"avg_assist_response_seconds"`
	AvgAssistResolutionSeconds float64            `json:"avg_assist_resolution_seconds"`
	AnomalyCount               int32              `json:"anomaly_count"`
	ProjectedAt                pgtype.Timestamptz `json:"projected_at"`
	GroupName                  string             `json:"group_name"`
}

func (q *Queries) ListDailyFloorMetrics(ctx context.Context, arg ListDailyFloorMetricsParams) ([]ListDailyFloorMetricsRow, error) {
	rows, err := q.db.Query(ctx, listDailyFloorMetrics,
		arg.OrganisationID,
		arg.LocationID,
		arg.MetricDate,
		arg.MetricDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailyFloorMetricsRow{}
	for rows.Next() {
		var i ListDailyFloorMetricsRow
		if err := rows.Scan(
			&i.OrganisationID,
			&i.LocationID,
			&i.FloorID,
			&i.MetricDate,
			&i.BucketStart,
			&i.BucketEnd,
			&i.ActiveTableCount,
			&i.OccupancySeconds,
			&i.UtilisationBasisSeconds,
			&i.UtilisationRate,
			&i.CompletedSessionCount,
			&i.TurnoverRate,
			&i.AvgSessionSeconds,
			&i.P50SessionSeconds,
			&i.P90SessionSeconds,
			&i.AssistRequestCount,
			&i.AvgAssistResponseSeconds,
			&i.AvgAssistResolutionSeconds,
			&i.AnomalyCount,
			&i.ProjectedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyLocationMetrics = `-- name: ListDailyLocationMetrics :many
SELECT organisation_id, location_id, metric_date, bucket_start, bucket_end, active_table_count, occupancy_seconds, utilisation_basis_seconds, utilisation_rate, completed_session_count, turnover_rate, avg_session_seconds, p50_session_seconds, p90_session_seconds, assist_request_count, avg_assist_response_seconds, avg_assist_resolution_seconds, anomaly_count, projected_at
FROM analytics_daily_location_metrics
WHERE organisation_id = $1
  AND location_id = $2
  AND metric_date >= $3
  AND metric_date < $4
ORDER BY metric_date
`

type ListDailyLocationMetricsParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	MetricDate     pgtype.Date `json:"metric_date"`
	MetricDate_2   pgtype.Date `json:"metric_date_2"`
}

func (q *Queries) ListDailyLocationMetrics(ctx context.Context, arg ListDailyLocationMetricsParams) ([]AnalyticsDailyLocationMetric, error) {
	rows, err := q.db.Query(ctx, listDailyLocationMetrics,
		arg.OrganisationID,
		arg.LocationID,
		arg.MetricDate,
		arg.MetricDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsDailyLocationMetric{}
	for rows.Next() {
		var i AnalyticsDailyLocationMetric
		if err := rows.Scan(
			&i.OrganisationID,
			&i.LocationID,
			&i.MetricDate,
			&i.BucketStart,
			&i.BucketEnd,
			&i.ActiveTableCount,
			&i.OccupancySeconds,
			&i.UtilisationBasisSeconds,
			&i.UtilisationRate,
			&i.CompletedSessionCount,
			&i.TurnoverRate,
			&i.AvgSessionSeconds,
			&i.P50SessionSeconds,
			&i.P90SessionSeconds,
			&i.AssistRequestCount,
			&i.AvgAssistResponseSeconds,
			&i.AvgAssistResolutionSeconds,
			&i.AnomalyCount,
			&i.ProjectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyZoneMetrics = `-- name: ListDailyZoneMetrics :many
SELECT m.organisation_id, m.location_id, m.zone_id, m.metric_date, m.bucket_start, m.bucket_end, m.active_table_count, m.occupancy_seconds, m.utilisation_basis_seconds, m.utilisation_rate, m.completed_session_count, m.turnover_rate, m.avg_session_seconds, m.p50_session_seconds, m.p90_session_seconds, m.assist_request_count, m.avg_assist_response_seconds, m.avg_assist_resolution_seconds, m.anomaly_count, m.projected_at, z.name AS group_name
FROM analytics_daily_zone_metrics m
JOIN zones z ON z.id = m.zone_id
WHERE m.organisation_id = $1
  AND m.location_id = $2
  AND m.metric_date >= $3
  AND m.metric_date < $4
ORDER BY z.sort_order, z.name, m.metric_date
`

type ListDailyZoneMetricsParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	MetricDate     pgtype.Date `json:"metric_date"`
	MetricDate_2   pgtype.Date `json:"metric_date_2"`
}

type ListDailyZoneMetricsRow struct {
	OrganisationID             uuid.UUID          `json:"organisation_id"`
	LocationID                 uuid.UUID          `json:"location_id"`
	ZoneID                     uuid.UUID          `json:"zone_id"`
	MetricDate                 pgtype.Date        `json:"metric_date"`
	BucketStart                pgtype.Timestamptz `json:"bucket_start"`
	BucketEnd                  pgtype.Timestamptz `json:"bucket_end"`
	ActiveTableCount           int32              `json:"active_table_count"`
	OccupancySeconds           float64            `json:"occupancy_seconds"`
	UtilisationBasisSeconds    float64            `json:"utilisation_basis_seconds"`
	UtilisationRate            float64            `json:"utilisation_rate"`
	CompletedSessionCount      int32              `json:"completed_session_count"`
	TurnoverRate               float64            `json:"turnover_rate"`
	AvgSessionSeconds          float64            `json:"avg_session_seconds"`
	P50SessionSeconds          float64            `json:"p50_session_seconds"`
	P90SessionSeconds          float64            `json:"p90_session_seconds"`
	AssistRequestCount         int32              `json:"assist_request_count"`
	AvgAssistResponseSeconds   float64            `json:"avg_assist_response_seconds"`
	AvgAssistResolutionSeconds float64            `json:"avg_assist_resolution_seconds"`
	AnomalyCount               int32              `json:"anomaly_count"`
	ProjectedAt                pgtype.Timestamptz `json:"projected_at"`
	GroupName                  string             `json:"group_name"`
}

func (q *Queries) ListDailyZoneMetrics(ctx context.Context, arg ListDailyZoneMetricsParams) ([]ListDailyZoneMetricsRow, error) {
	rows, err := q.db.Query(ctx, listDailyZoneMetrics,
		arg.OrganisationID,
		arg.LocationID,
		arg.MetricDate,
		arg.MetricDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailyZoneMetricsRow{}
	for rows.Next() {
		var i ListDailyZoneMetricsRow
		if err := rows.Scan(
			&i.OrganisationID,
			&i.LocationID,
			&i.ZoneID,
			&i.MetricDate,
			&i.BucketStart,
			&i.BucketEnd,
			&i.ActiveTableCount,
			&i.OccupancySeconds,
			&i.UtilisationBasisSeconds,
			&i.UtilisationRate,
			&i.CompletedSessionCount,
			&i.TurnoverRate,
			&i.AvgSessionSeconds,
			&i.P50SessionSeconds,
			&i.P90SessionSeconds,
			&i.AssistRequestCount,
			&i.AvgAssistResponseSeconds,
			&i.AvgAssistResolutionSeconds,
			&i.AnomalyCount,
			&i.ProjectedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHourlyTableMetrics = `-- name: ListHourlyTableMetrics :many
SELECT organisation_id, location_id, table_id, bucket_start, bucket_end, active_table_count, occupancy_seconds, utilisation_basis_seconds, utilisation_rate, completed_session_count, turnover_rate, avg_session_seconds, p50_session_seconds, p90_session_seconds, assist_request_count, avg_assist_response_seconds, avg_assist_resolution_seconds, anomaly_count, projected_at
FROM analytics_hourly_table_metrics
WHERE organisation_id = $1
  AND location_id = $2
  AND bucket_start >= $3
  AND bucket_start < $4
ORDER BY bucket_start, table_id
`

type ListHourlyTableMetricsParams struct {
	OrganisationID uuid.UUID          `json:"organisation_id"`
	LocationID     uuid.UUID          `json:"location_id"`
	BucketStart    pgtype.Timestamptz `json:"bucket_start"`
	BucketStart_2  pgtype.Timestamptz `json:"bucket_start_2"`
}

func (q *Queries) ListHourlyTableMetrics(ctx context.Context, arg ListHourlyTableMetricsParams) ([]AnalyticsHourlyTableMetric, error) {
	rows, err := q.db.Query(ctx, listHourlyTableMetrics,
		arg.OrganisationID,
		arg.LocationID,
		arg.BucketStart,
		arg.BucketStart_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsHourlyTableMetric{}
	for rows.Next() {
		var i AnalyticsHourlyTableMetric
		if err := rows.Scan(
			&i.OrganisationID,
			&i.LocationID,
			&i.TableID,
			&i.BucketStart,
			&i.BucketEnd,
			&i.ActiveTableCount,
			&i.OccupancySeconds,
			&i.UtilisationBasisSeconds,
			&i.UtilisationRate,
			&i.CompletedSessionCount,
			&i.TurnoverRate,
			&i.AvgSessionSeconds,
			&i.P50SessionSeconds,
			&i.P90SessionSeconds,
			&i.AssistRequestCount,
			&i.AvgAssistResponseSeconds,
			&i.AvgAssistResolutionSeconds,
			&i.AnomalyCount,
			&i.ProjectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicePeriodMetrics = `-- name: ListServicePeriodMetrics :many
SELECT m.organisation_id, m.location_id, m.service_period_id, m.metric_date, m.bucket_start, m.bucket_end, m.active_table_count, m.occupancy_seconds, m.utilisation_basis_seconds, m.utilisation_rate, m.completed_session_count, m.turnover_rate, m.avg_session_seconds, m.p50_session_seconds, m.p90_session_seconds, m.assist_request_count, m.avg_assist_response_seconds, m.avg_assist_resolution_seconds, m.anomaly_count, m.projected_at, sp.name AS group_name
FROM analytics_service_period_metrics m
JOIN service_periods sp ON sp.id = m.service_period_id
WHERE m.organisation_id = $1
  AND m.location_id = $2
  AND m.metric_date >= $3
  AND m.metric_date < $4
ORDER BY sp.name, m.metric_date
`

type ListServicePeriodMetricsParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	MetricDate     pgtype.Date `json:"metric_date"`
	MetricDate_2   pgtype.Date `json:"metric_date_2"`
}

type ListServicePeriodMetricsRow struct {
	OrganisationID             uuid.UUID          `json:"organisation_id"`
	LocationID                 uuid.UUID          `json:"location_id"`
	ServicePeriodID            uuid.UUID          `json:"service_period_id"`
	MetricDate                 pgtype.Date        `json:"metric_date"`
	BucketStart                pgtype.Timestamptz `json:"bucket_start"`
	BucketEnd                  pgtype.Timestamptz `json:"bucket_end"`
	ActiveTableCount           int32              `json:"active_table_count"`
	OccupancySeconds           float64            `json:"occupancy_seconds"`
	UtilisationBasisSeconds    float64            `json:"utilisation_basis_seconds"`
	UtilisationRate            float64            `json:"utilisation_rate"`
	CompletedSessionCount      int32              `json:"completed_session_count"`
	TurnoverRate               float64            `json:"turnover_rate"`
	AvgSessionSeconds          float64            `json:"avg_session_seconds"`
	P50SessionSeconds          float64            `json:"p50_session_seconds"`
	P90SessionSeconds          float64            `json:"p90_session_seconds"`
	AssistRequestCount         int32              `json:"assist_request_count"`
	AvgAssistResponseSeconds   float64            `json:"avg_assist_response_seconds"`
	AvgAssistResolutionSeconds float64            `json:"avg_assist_resolution_seconds"`
	AnomalyCount               int32              `json:"anomaly_count"`
	ProjectedAt                pgtype.Timestamptz `json:"projected_at"`
	GroupName                  string             `json:"group_name"`
}

func (q *Queries) ListServicePeriodMetrics(ctx context.Context, arg ListServicePeriodMetricsParams) ([]ListServicePeriodMetricsRow, error) {
	rows, err := q.db.Query(ctx, listServicePeriodMetrics,
		arg.OrganisationID,
		arg.LocationID,
		arg.MetricDate,
		arg.MetricDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicePeriodMetricsRow{}
	for rows.Next() {
		var i ListServicePeriodMetricsRow
		if err := rows.Scan(
			&i.OrganisationID,
			&i.LocationID,
			&i.ServicePeriodID,
			&i.MetricDate,
			&i.BucketStart,
			&i.BucketEnd,
			&i.ActiveTableCount,
			&i.OccupancySeconds,
			&i.UtilisationBasisSeconds,
			&i.UtilisationRate,
			&i.CompletedSessionCount,
			&i.TurnoverRate,
			&i.AvgSessionSeconds,
			&i.P50SessionSeconds,
			&i.P90SessionSeconds,
			&i.AssistRequestCount,
			&i.AvgAssistResponseSeconds,
			&i.AvgAssistResolutionSeconds,
			&i.AnomalyCount,
			&i.ProjectedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicePeriodsByLocation = `-- name: ListServicePeriodsByLocation :many
SELECT id, organisation_id, location_id, name, days_of_week, start_time, end_time, is_active, version, created_at, updated_at
FROM service_periods
WHERE organisation_id = $1
  AND location_id = $2
ORDER BY is_active DESC, name
`

type ListServicePeriodsByLocationParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

func (q *Queries) ListServicePeriodsByLocation(ctx context.Context, arg ListServicePeriodsByLocationParams) ([]ServicePeriod, error) {
	rows, err := q.db.Query(ctx, listServicePeriodsByLocation, arg.OrganisationID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServicePeriod{}
	for rows.Next() {
		var i ServicePeriod
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.Name,
			&i.DaysOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServicePeriod = `-- name: UpdateServicePeriod :one
UPDATE service_periods
SET name = $4,
    days_of_week = $5,
    start_time = $6,
    end_time = $7,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND version = $8
RETURNING id, organisation_id, location_id, name, days_of_week, start_time, end_time, is_active, version, created_at, updated_at
`

type UpdateServicePeriodParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	Name           string      `json:"name"`
	DaysOfWeek     []int16     `json:"days_of_week"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
	Version        int32       `json:"version"`
}

func (q *Queries) UpdateServicePeriod(ctx context.Context, arg UpdateServicePeriodParams) (ServicePeriod, error) {
	row := q.db.QueryRow(ctx, updateServicePeriod,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.Name,
		arg.DaysOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Version,
	)
	var i ServicePeriod
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.Name,
		&i.DaysOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
