// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: layout.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveFloor = `-- name: ArchiveFloor :one
UPDATE floors
SET is_active = false,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND version = $4
RETURNING id, organisation_id, location_id, slug, name, sort_order, canvas, background_asset_ref, is_active, version, created_at, updated_at
`

type ArchiveFloorParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	Version        int32     `json:"version"`
}

func (q *Queries) ArchiveFloor(ctx context.Context, arg ArchiveFloorParams) (Floor, error) {
	row := q.db.QueryRow(ctx, archiveFloor,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.Version,
	)
	var i Floor
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.Slug,
		&i.Name,
		&i.SortOrder,
		&i.Canvas,
		&i.BackgroundAssetRef,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveTable = `-- name: ArchiveTable :one
UPDATE tables
SET is_active = false,
    deleted_at = now(),
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND version = $4
RETURNING id, organisation_id, location_id, floor_id, zone_id, label, capacity_label, shape, geometry, is_active, deleted_at, version, legacy_table_id, created_at, updated_at
`

type ArchiveTableParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	Version        int32     `json:"version"`
}

func (q *Queries) ArchiveTable(ctx context.Context, arg ArchiveTableParams) (Table, error) {
	row := q.db.QueryRow(ctx, archiveTable,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.Version,
	)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.FloorID,
		&i.ZoneID,
		&i.Label,
		&i.CapacityLabel,
		&i.Shape,
		&i.Geometry,
		&i.IsActive,
		&i.DeletedAt,
		&i.Version,
		&i.LegacyTableID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveZone = `-- name: ArchiveZone :one
UPDATE zones
SET is_active = false,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND floor_id = $4
  AND version = $5
RETURNING id, organisation_id, location_id, floor_id, name, sort_order, is_active, version, created_at, updated_at
`

type ArchiveZoneParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	FloorID        uuid.UUID `json:"floor_id"`
	Version        int32     `json:"version"`
}

func (q *Queries) ArchiveZone(ctx context.Context, arg ArchiveZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, archiveZone,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.FloorID,
		arg.Version,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.FloorID,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFloor = `-- name: CreateFloor :one
INSERT INTO floors (
    organisation_id,
    location_id,
    slug,
    name,
    sort_order,
    canvas,
    background_asset_ref
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organisation_id, location_id, slug, name, sort_order, canvas, background_asset_ref, is_active, version, created_at, updated_at
`

type CreateFloorParams struct {
	OrganisationID     uuid.UUID   `json:"organisation_id"`
	LocationID         uuid.UUID   `json:"location_id"`
	Slug               string      `json:"slug"`
	Name               string      `json:"name"`
	SortOrder          int32       `json:"sort_order"`
	Canvas             []byte      `json:"canvas"`
	BackgroundAssetRef pgtype.Text `json:"background_asset_ref"`
}

func (q *Queries) CreateFloor(ctx context.Context, arg CreateFloorParams) (Floor, error) {
	row := q.db.QueryRow(ctx, createFloor,
		arg.OrganisationID,
		arg.LocationID,
		arg.Slug,
		arg.Name,
		arg.SortOrder,
		arg.Canvas,
		arg.BackgroundAssetRef,
	)
	var i Floor
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.Slug,
		&i.Name,
		&i.SortOrder,
		&i.Canvas,
		&i.BackgroundAssetRef,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTable = `-- name: CreateTable :one
INSERT INTO tables (
    organisation_id,
    location_id,
    floor_id,
    zone_id,
    label,
    capacity_label,
    shape,
    geometry,
    legacy_table_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organisation_id, location_id, floor_id, zone_id, label, capacity_label, shape, geometry, is_active, deleted_at, version, legacy_table_id, created_at, updated_at
`

type CreateTableParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	FloorID        uuid.UUID   `json:"floor_id"`
	ZoneID         uuid.UUID   `json:"zone_id"`
	Label          string      `json:"label"`
	CapacityLabel  string      `json:"capacity_label"`
	Shape          string      `json:"shape"`
	Geometry       []byte      `json:"geometry"`
	LegacyTableID  pgtype.Text `json:"legacy_table_id"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (Table, error) {
	row := q.db.QueryRow(ctx, createTable,
		arg.OrganisationID,
		arg.LocationID,
		arg.FloorID,
		arg.ZoneID,
		arg.Label,
		arg.CapacityLabel,
		arg.Shape,
		arg.Geometry,
		arg.LegacyTableID,
	)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.FloorID,
		&i.ZoneID,
		&i.Label,
		&i.CapacityLabel,
		&i.Shape,
		&i.Geometry,
		&i.IsActive,
		&i.DeletedAt,
		&i.Version,
		&i.LegacyTableID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTableOccupancy = `-- name: CreateTableOccupancy :one
INSERT INTO table_occupancy (table_id, organisation_id, location_id)
VALUES ($1, $2, $3)
RETURNING table_id, organisation_id, location_id, status, current_session_id, version, updated_by, updated_at, created_at
`

type CreateTableOccupancyParams struct {
	TableID        uuid.UUID `json:"table_id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

func (q *Queries) CreateTableOccupancy(ctx context.Context, arg CreateTableOccupancyParams) (TableOccupancy, error) {
	row := q.db.QueryRow(ctx, createTableOccupancy, arg.TableID, arg.OrganisationID, arg.LocationID)
	var i TableOccupancy
	err := row.Scan(
		&i.TableID,
		&i.OrganisationID,
		&i.LocationID,
		&i.Status,
		&i.CurrentSessionID,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTableQRCapability = `-- name: CreateTableQRCapability :one
INSERT INTO table_qr_capabilities (
    organisation_id,
    location_id,
    table_id,
    token,
    token_lookup_prefix,
    token_hash,
    label,
    expires_at
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    left($4::text, 16),
    left($4::text, 16),
    digest($4::text, 'sha256'),
    $5::text,
    $6::timestamptz
)
RETURNING id, organisation_id, location_id, table_id, token, label, issued_at, expires_at, revoked_at, version, created_at, updated_at, token_lookup_prefix, token_hash, last_used_at
`

type CreateTableQRCapabilityParams struct {
	OrganisationID uuid.UUID          `json:"organisation_id"`
	LocationID     uuid.UUID          `json:"location_id"`
	TableID        uuid.UUID          `json:"table_id"`
	Token          string             `json:"token"`
	Label          string             `json:"label"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTableQRCapability(ctx context.Context, arg CreateTableQRCapabilityParams) (TableQrCapability, error) {
	row := q.db.QueryRow(ctx, createTableQRCapability,
		arg.OrganisationID,
		arg.LocationID,
		arg.TableID,
		arg.Token,
		arg.Label,
		arg.ExpiresAt,
	)
	var i TableQrCapability
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.Token,
		&i.Label,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenLookupPrefix,
		&i.TokenHash,
		&i.LastUsedAt,
	)
	return i, err
}

const createZone = `-- name: CreateZone :one
INSERT INTO zones (organisation_id, location_id, floor_id, name, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organisation_id, location_id, floor_id, name, sort_order, is_active, version, created_at, updated_at
`

type CreateZoneParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	FloorID        uuid.UUID `json:"floor_id"`
	Name           string    `json:"name"`
	SortOrder      int32     `json:"sort_order"`
}

func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, createZone,
		arg.OrganisationID,
		arg.LocationID,
		arg.FloorID,
		arg.Name,
		arg.SortOrder,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.FloorID,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTableDetail = `-- name: GetTableDetail :one
SELECT t.id, t.organisation_id, t.location_id, t.floor_id, t.zone_id, t.label, t.capacity_label, t.shape, t.geometry, t.is_active, t.deleted_at, t.version, t.legacy_table_id, t.created_at, t.updated_at, o.table_id, o.organisation_id, o.location_id, o.status, o.current_session_id, o.version, o.updated_by, o.updated_at, o.created_at
FROM tables t
JOIN table_occupancy o ON o.table_id = t.id
WHERE t.id = $1
  AND t.organisation_id = $2
  AND t.location_id = $3
  AND t.is_active
  AND t.deleted_at IS NULL
`

type GetTableDetailParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

type GetTableDetailRow struct {
	Table          Table          `json:"table"`
	TableOccupancy TableOccupancy `json:"table_occupancy"`
}

func (q *Queries) GetTableDetail(ctx context.Context, arg GetTableDetailParams) (GetTableDetailRow, error) {
	row := q.db.QueryRow(ctx, getTableDetail, arg.ID, arg.OrganisationID, arg.LocationID)
	var i GetTableDetailRow
	err := row.Scan(
		&i.Table.ID,
		&i.Table.OrganisationID,
		&i.Table.LocationID,
		&i.Table.FloorID,
		&i.Table.ZoneID,
		&i.Table.Label,
		&i.Table.CapacityLabel,
		&i.Table.Shape,
		&i.Table.Geometry,
		&i.Table.IsActive,
		&i.Table.DeletedAt,
		&i.Table.Version,
		&i.Table.LegacyTableID,
		&i.Table.CreatedAt,
		&i.Table.UpdatedAt,
		&i.TableOccupancy.TableID,
		&i.TableOccupancy.OrganisationID,
		&i.TableOccupancy.LocationID,
		&i.TableOccupancy.Status,
		&i.TableOccupancy.CurrentSessionID,
		&i.TableOccupancy.Version,
		&i.TableOccupancy.UpdatedBy,
		&i.TableOccupancy.UpdatedAt,
		&i.TableOccupancy.CreatedAt,
	)
	return i, err
}

const listAllFloorsByLocation = `-- name: ListAllFloorsByLocation :many
SELECT id, organisation_id, location_id, slug, name, sort_order, canvas, background_asset_ref, is_active, version, created_at, updated_at
FROM floors
WHERE organisation_id = $1 AND location_id = $2
ORDER BY is_active DESC, sort_order, name
`

type ListAllFloorsByLocationParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

func (q *Queries) ListAllFloorsByLocation(ctx context.Context, arg ListAllFloorsByLocationParams) ([]Floor, error) {
	rows, err := q.db.Query(ctx, listAllFloorsByLocation, arg.OrganisationID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Floor{}
	for rows.Next() {
		var i Floor
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.Slug,
			&i.Name,
			&i.SortOrder,
			&i.Canvas,
			&i.BackgroundAssetRef,
			&i.IsActive,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTablesByLocation = `-- name: ListAllTablesByLocation :many
SELECT id, organisation_id, location_id, floor_id, zone_id, label, capacity_label, shape, geometry, is_active, deleted_at, version, legacy_table_id, created_at, updated_at
FROM tables
WHERE organisation_id = $1
  AND location_id = $2
ORDER BY is_active DESC, deleted_at NULLS FIRST, floor_id, label
`

type ListAllTablesByLocationParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

func (q *Queries) ListAllTablesByLocation(ctx context.Context, arg ListAllTablesByLocationParams) ([]Table, error) {
	rows, err := q.db.Query(ctx, listAllTablesByLocation, arg.OrganisationID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.FloorID,
			&i.ZoneID,
			&i.Label,
			&i.CapacityLabel,
			&i.Shape,
			&i.Geometry,
			&i.IsActive,
			&i.DeletedAt,
			&i.Version,
			&i.LegacyTableID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllZonesByLocation = `-- name: ListAllZonesByLocation :many
SELECT id, organisation_id, location_id, floor_id, name, sort_order, is_active, version, created_at, updated_at
FROM zones
WHERE organisation_id = $1 AND location_id = $2
ORDER BY is_active DESC, floor_id, sort_order, name
`

type ListAllZonesByLocationParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

func (q *Queries) ListAllZonesByLocation(ctx context.Context, arg ListAllZonesByLocationParams) ([]Zone, error) {
	rows, err := q.db.Query(ctx, listAllZonesByLocation, arg.OrganisationID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Zone{}
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.FloorID,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFloorsByLocation = `-- name: ListFloorsByLocation :many
SELECT id, organisation_id, location_id, slug, name, sort_order, canvas, background_asset_ref, is_active, version, created_at, updated_at
FROM floors
WHERE organisation_id = $1 AND location_id = $2 AND is_active
ORDER BY sort_order, name
`

type ListFloorsByLocationParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

func (q *Queries) ListFloorsByLocation(ctx context.Context, arg ListFloorsByLocationParams) ([]Floor, error) {
	rows, err := q.db.Query(ctx, listFloorsByLocation, arg.OrganisationID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Floor{}
	for rows.Next() {
		var i Floor
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.Slug,
			&i.Name,
			&i.SortOrder,
			&i.Canvas,
			&i.BackgroundAssetRef,
			&i.IsActive,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationTableStates = `-- name: ListLocationTableStates :many
SELECT t.id, t.organisation_id, t.location_id, t.floor_id, t.zone_id, t.label, t.capacity_label, t.shape, t.geometry, t.is_active, t.deleted_at, t.version, t.legacy_table_id, t.created_at, t.updated_at, o.table_id, o.organisation_id, o.location_id, o.status, o.current_session_id, o.version, o.updated_by, o.updated_at, o.created_at
FROM tables t
JOIN table_occupancy o ON o.table_id = t.id
WHERE t.organisation_id = $1
  AND t.location_id = $2
  AND t.is_active
  AND t.deleted_at IS NULL
ORDER BY t.label
`

type ListLocationTableStatesParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

type ListLocationTableStatesRow struct {
	Table          Table          `json:"table"`
	TableOccupancy TableOccupancy `json:"table_occupancy"`
}

func (q *Queries) ListLocationTableStates(ctx context.Context, arg ListLocationTableStatesParams) ([]ListLocationTableStatesRow, error) {
	rows, err := q.db.Query(ctx, listLocationTableStates, arg.OrganisationID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocationTableStatesRow{}
	for rows.Next() {
		var i ListLocationTableStatesRow
		if err := rows.Scan(
			&i.Table.ID,
			&i.Table.OrganisationID,
			&i.Table.LocationID,
			&i.Table.FloorID,
			&i.Table.ZoneID,
			&i.Table.Label,
			&i.Table.CapacityLabel,
			&i.Table.Shape,
			&i.Table.Geometry,
			&i.Table.IsActive,
			&i.Table.DeletedAt,
			&i.Table.Version,
			&i.Table.LegacyTableID,
			&i.Table.CreatedAt,
			&i.Table.UpdatedAt,
			&i.TableOccupancy.TableID,
			&i.TableOccupancy.OrganisationID,
			&i.TableOccupancy.LocationID,
			&i.TableOccupancy.Status,
			&i.TableOccupancy.CurrentSessionID,
			&i.TableOccupancy.Version,
			&i.TableOccupancy.UpdatedBy,
			&i.TableOccupancy.UpdatedAt,
			&i.TableOccupancy.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTableStatesByLocationIncludingArchived = `-- name: ListTableStatesByLocationIncludingArchived :many
SELECT t.id, t.organisation_id, t.location_id, t.floor_id, t.zone_id, t.label, t.capacity_label, t.shape, t.geometry, t.is_active, t.deleted_at, t.version, t.legacy_table_id, t.created_at, t.updated_at, o.table_id, o.organisation_id, o.location_id, o.status, o.current_session_id, o.version, o.updated_by, o.updated_at, o.created_at
FROM tables t
LEFT JOIN table_occupancy o ON o.table_id = t.id
WHERE t.organisation_id = $1
  AND t.location_id = $2
ORDER BY t.floor_id, t.label
`

type ListTableStatesByLocationIncludingArchivedParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

type ListTableStatesByLocationIncludingArchivedRow struct {
	Table          Table          `json:"table"`
	TableOccupancy TableOccupancy `json:"table_occupancy"`
}

func (q *Queries) ListTableStatesByLocationIncludingArchived(ctx context.Context, arg ListTableStatesByLocationIncludingArchivedParams) ([]ListTableStatesByLocationIncludingArchivedRow, error) {
	rows, err := q.db.Query(ctx, listTableStatesByLocationIncludingArchived, arg.OrganisationID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTableStatesByLocationIncludingArchivedRow{}
	for rows.Next() {
		var i ListTableStatesByLocationIncludingArchivedRow
		if err := rows.Scan(
			&i.Table.ID,
			&i.Table.OrganisationID,
			&i.Table.LocationID,
			&i.Table.FloorID,
			&i.Table.ZoneID,
			&i.Table.Label,
			&i.Table.CapacityLabel,
			&i.Table.Shape,
			&i.Table.Geometry,
			&i.Table.IsActive,
			&i.Table.DeletedAt,
			&i.Table.Version,
			&i.Table.LegacyTableID,
			&i.Table.CreatedAt,
			&i.Table.UpdatedAt,
			&i.TableOccupancy.TableID,
			&i.TableOccupancy.OrganisationID,
			&i.TableOccupancy.LocationID,
			&i.TableOccupancy.Status,
			&i.TableOccupancy.CurrentSessionID,
			&i.TableOccupancy.Version,
			&i.TableOccupancy.UpdatedBy,
			&i.TableOccupancy.UpdatedAt,
			&i.TableOccupancy.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTablesByFloor = `-- name: ListTablesByFloor :many
SELECT id, organisation_id, location_id, floor_id, zone_id, label, capacity_label, shape, geometry, is_active, deleted_at, version, legacy_table_id, created_at, updated_at
FROM tables
WHERE organisation_id = $1
  AND location_id = $2
  AND floor_id = $3
  AND is_active
  AND deleted_at IS NULL
ORDER BY label
`

type ListTablesByFloorParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	FloorID        uuid.UUID `json:"floor_id"`
}

func (q *Queries) ListTablesByFloor(ctx context.Context, arg ListTablesByFloorParams) ([]Table, error) {
	rows, err := q.db.Query(ctx, listTablesByFloor, arg.OrganisationID, arg.LocationID, arg.FloorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.FloorID,
			&i.ZoneID,
			&i.Label,
			&i.CapacityLabel,
			&i.Shape,
			&i.Geometry,
			&i.IsActive,
			&i.DeletedAt,
			&i.Version,
			&i.LegacyTableID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZonesByFloor = `-- name: ListZonesByFloor :many
SELECT id, organisation_id, location_id, floor_id, name, sort_order, is_active, version, created_at, updated_at
FROM zones
WHERE organisation_id = $1 AND location_id = $2 AND floor_id = $3 AND is_active
ORDER BY sort_order, name
`

type ListZonesByFloorParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	FloorID        uuid.UUID `json:"floor_id"`
}

func (q *Queries) ListZonesByFloor(ctx context.Context, arg ListZonesByFloorParams) ([]Zone, error) {
	rows, err := q.db.Query(ctx, listZonesByFloor, arg.OrganisationID, arg.LocationID, arg.FloorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Zone{}
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.FloorID,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreFloor = `-- name: RestoreFloor :one
UPDATE floors
SET is_active = true,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND version = $4
RETURNING id, organisation_id, location_id, slug, name, sort_order, canvas, background_asset_ref, is_active, version, created_at, updated_at
`

type RestoreFloorParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	Version        int32     `json:"version"`
}

func (q *Queries) RestoreFloor(ctx context.Context, arg RestoreFloorParams) (Floor, error) {
	row := q.db.QueryRow(ctx, restoreFloor,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.Version,
	)
	var i Floor
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.Slug,
		&i.Name,
		&i.SortOrder,
		&i.Canvas,
		&i.BackgroundAssetRef,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restoreTable = `-- name: RestoreTable :one
UPDATE tables
SET is_active = true,
    deleted_at = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND version = $4
RETURNING id, organisation_id, location_id, floor_id, zone_id, label, capacity_label, shape, geometry, is_active, deleted_at, version, legacy_table_id, created_at, updated_at
`

type RestoreTableParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	Version        int32     `json:"version"`
}

func (q *Queries) RestoreTable(ctx context.Context, arg RestoreTableParams) (Table, error) {
	row := q.db.QueryRow(ctx, restoreTable,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.Version,
	)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.FloorID,
		&i.ZoneID,
		&i.Label,
		&i.CapacityLabel,
		&i.Shape,
		&i.Geometry,
		&i.IsActive,
		&i.DeletedAt,
		&i.Version,
		&i.LegacyTableID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFloor = `-- name: UpdateFloor :one
UPDATE floors
SET slug = $4,
    name = $5,
    sort_order = $6,
    canvas = $7,
    background_asset_ref = $8,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND version = $9
RETURNING id, organisation_id, location_id, slug, name, sort_order, canvas, background_asset_ref, is_active, version, created_at, updated_at
`

type UpdateFloorParams struct {
	ID                 uuid.UUID   `json:"id"`
	OrganisationID     uuid.UUID   `json:"organisation_id"`
	LocationID         uuid.UUID   `json:"location_id"`
	Slug               string      `json:"slug"`
	Name               string      `json:"name"`
	SortOrder          int32       `json:"sort_order"`
	Canvas             []byte      `json:"canvas"`
	BackgroundAssetRef pgtype.Text `json:"background_asset_ref"`
	Version            int32       `json:"version"`
}

func (q *Queries) UpdateFloor(ctx context.Context, arg UpdateFloorParams) (Floor, error) {
	row := q.db.QueryRow(ctx, updateFloor,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.Slug,
		arg.Name,
		arg.SortOrder,
		arg.Canvas,
		arg.BackgroundAssetRef,
		arg.Version,
	)
	var i Floor
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.Slug,
		&i.Name,
		&i.SortOrder,
		&i.Canvas,
		&i.BackgroundAssetRef,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTable = `-- name: UpdateTable :one
UPDATE tables
SET floor_id = $4,
    zone_id = $5,
    label = $6,
    capacity_label = $7,
    shape = $8,
    geometry = $9,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND version = $10
RETURNING id, organisation_id, location_id, floor_id, zone_id, label, capacity_label, shape, geometry, is_active, deleted_at, version, legacy_table_id, created_at, updated_at
`

type UpdateTableParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	FloorID        uuid.UUID `json:"floor_id"`
	ZoneID         uuid.UUID `json:"zone_id"`
	Label          string    `json:"label"`
	CapacityLabel  string    `json:"capacity_label"`
	Shape          string    `json:"shape"`
	Geometry       []byte    `json:"geometry"`
	Version        int32     `json:"version"`
}

func (q *Queries) UpdateTable(ctx context.Context, arg UpdateTableParams) (Table, error) {
	row := q.db.QueryRow(ctx, updateTable,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.FloorID,
		arg.ZoneID,
		arg.Label,
		arg.CapacityLabel,
		arg.Shape,
		arg.Geometry,
		arg.Version,
	)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.FloorID,
		&i.ZoneID,
		&i.Label,
		&i.CapacityLabel,
		&i.Shape,
		&i.Geometry,
		&i.IsActive,
		&i.DeletedAt,
		&i.Version,
		&i.LegacyTableID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateZone = `-- name: UpdateZone :one
UPDATE zones
SET name = $5,
    sort_order = $6,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND floor_id = $4
  AND version = $7
RETURNING id, organisation_id, location_id, floor_id, name, sort_order, is_active, version, created_at, updated_at
`

type UpdateZoneParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	FloorID        uuid.UUID `json:"floor_id"`
	Name           string    `json:"name"`
	SortOrder      int32     `json:"sort_order"`
	Version        int32     `json:"version"`
}

func (q *Queries) UpdateZone(ctx context.Context, arg UpdateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, updateZone,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.FloorID,
		arg.Name,
		arg.SortOrder,
		arg.Version,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.FloorID,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
