// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AnalyticsDailyFloorMetric struct {
	OrganisationID             uuid.UUID          `json:"organisation_id"`
	LocationID                 uuid.UUID          `json:"location_id"`
	FloorID                    uuid.UUID          `json:"floor_id"`
	MetricDate                 pgtype.Date        `json:"metric_date"`
	BucketStart                pgtype.Timestamptz `json:"bucket_start"`
	BucketEnd                  pgtype.Timestamptz `json:"bucket_end"`
	ActiveTableCount           int32              `json:"active_table_count"`
	OccupancySeconds           float64            `json:"occupancy_seconds"`
	UtilisationBasisSeconds    float64            `json:"utilisation_basis_seconds"`
	UtilisationRate            float64            `json:"utilisation_rate"`
	CompletedSessionCount      int32              `json:"completed_session_count"`
	TurnoverRate               float64            `json:"turnover_rate"`
	AvgSessionSeconds          float64            `json:"avg_session_seconds"`
	P50SessionSeconds          float64            `json:"p50_session_seconds"`
	P90SessionSeconds          float64            `json:"p90_session_seconds"`
	AssistRequestCount         int32              `json:"assist_request_count"`
	AvgAssistResponseSeconds   float64            `json:"avg_assist_response_seconds"`
	AvgAssistResolutionSeconds float64            `json:"avg_assist_resolution_seconds"`
	AnomalyCount               int32              `json:"anomaly_count"`
	ProjectedAt                pgtype.Timestamptz `json:"projected_at"`
}

type AnalyticsDailyLocationMetric struct {
	OrganisationID             uuid.UUID          `json:"organisation_id"`
	LocationID                 uuid.UUID          `json:"location_id"`
	MetricDate                 pgtype.Date        `json:"metric_date"`
	BucketStart                pgtype.Timestamptz `json:"bucket_start"`
	BucketEnd                  pgtype.Timestamptz `json:"bucket_end"`
	ActiveTableCount           int32              `json:"active_table_count"`
	OccupancySeconds           float64            `json:"occupancy_seconds"`
	UtilisationBasisSeconds    float64            `json:"utilisation_basis_seconds"`
	UtilisationRate            float64            `json:"utilisation_rate"`
	CompletedSessionCount      int32              `json:"completed_session_count"`
	TurnoverRate               float64            `json:"turnover_rate"`
	AvgSessionSeconds          float64            `json:"avg_session_seconds"`
	P50SessionSeconds          float64            `json:"p50_session_seconds"`
	P90SessionSeconds          float64            `json:"p90_session_seconds"`
	AssistRequestCount         int32              `json:"assist_request_count"`
	AvgAssistResponseSeconds   float64            `json:"avg_assist_response_seconds"`
	AvgAssistResolutionSeconds float64            `json:"avg_assist_resolution_seconds"`
	AnomalyCount               int32              `json:"anomaly_count"`
	ProjectedAt                pgtype.Timestamptz `json:"projected_at"`
}

type AnalyticsDailyTableMetric struct {
	OrganisationID             uuid.UUID          `json:"organisation_id"`
	LocationID                 uuid.UUID          `json:"location_id"`
	TableID                    uuid.UUID          `json:"table_id"`
	MetricDate                 pgtype.Date        `json:"metric_date"`
	BucketStart                pgtype.Timestamptz `json:"bucket_start"`
	BucketEnd                  pgtype.Timestamptz `json:"bucket_end"`
	ActiveTableCount           int32              `json:"active_table_count"`
	OccupancySeconds           float64            `json:"occupancy_seconds"`
	UtilisationBasisSeconds    float64            `json:"utilisation_basis_seconds"`
	UtilisationRate            float64            `json:"utilisation_rate"`
	CompletedSessionCount      int32              `json:"completed_session_count"`
	TurnoverRate               float64            `json:"turnover_rate"`
	AvgSessionSeconds          float64            `json:"avg_session_seconds"`
	P50SessionSeconds          float64            `json:"p50_session_seconds"`
	P90SessionSeconds          float64            `json:"p90_session_seconds"`
	AssistRequestCount         int32              `json:"assist_request_count"`
	AvgAssistResponseSeconds   float64            `json:"avg_assist_response_seconds"`
	AvgAssistResolutionSeconds float64            `json:"avg_assist_resolution_seconds"`
	AnomalyCount               int32              `json:"anomaly_count"`
	ProjectedAt                pgtype.Timestamptz `json:"projected_at"`
}

type AnalyticsDailyZoneMetric struct {
	OrganisationID             uuid.UUID          `json:"organisation_id"`
	LocationID                 uuid.UUID          `json:"location_id"`
	ZoneID                     uuid.UUID          `json:"zone_id"`
	MetricDate                 pgtype.Date        `json:"metric_date"`
	BucketStart                pgtype.Timestamptz `json:"bucket_start"`
	BucketEnd                  pgtype.Timestamptz `json:"bucket_end"`
	ActiveTableCount           int32              `json:"active_table_count"`
	OccupancySeconds           float64            `json:"occupancy_seconds"`
	UtilisationBasisSeconds    float64            `json:"utilisation_basis_seconds"`
	UtilisationRate            float64            `json:"utilisation_rate"`
	CompletedSessionCount      int32              `json:"completed_session_count"`
	TurnoverRate               float64            `json:"turnover_rate"`
	AvgSessionSeconds          float64            `json:"avg_session_seconds"`
	P50SessionSeconds          float64            `json:"p50_session_seconds"`
	P90SessionSeconds          float64            `json:"p90_session_seconds"`
	AssistRequestCount         int32              `json:"assist_request_count"`
	AvgAssistResponseSeconds   float64            `json:"avg_assist_response_seconds"`
	AvgAssistResolutionSeconds float64            `json:"avg_assist_resolution_seconds"`
	AnomalyCount               int32              `json:"anomaly_count"`
	ProjectedAt                pgtype.Timestamptz `json:"projected_at"`
}

type AnalyticsHourlyTableMetric struct {
	OrganisationID             uuid.UUID          `json:"organisation_id"`
	LocationID                 uuid.UUID          `json:"location_id"`
	TableID                    uuid.UUID          `json:"table_id"`
	BucketStart                pgtype.Timestamptz `json:"bucket_start"`
	BucketEnd                  pgtype.Timestamptz `json:"bucket_end"`
	ActiveTableCount           int32              `json:"active_table_count"`
	OccupancySeconds           float64            `json:"occupancy_seconds"`
	UtilisationBasisSeconds    float64            `json:"utilisation_basis_seconds"`
	UtilisationRate            float64            `json:"utilisation_rate"`
	CompletedSessionCount      int32              `json:"completed_session_count"`
	TurnoverRate               float64            `json:"turnover_rate"`
	AvgSessionSeconds          float64            `json:"avg_session_seconds"`
	P50SessionSeconds          float64            `json:"p50_session_seconds"`
	P90SessionSeconds          float64            `json:"p90_session_seconds"`
	AssistRequestCount         int32              `json:"assist_request_count"`
	AvgAssistResponseSeconds   float64            `json:"avg_assist_response_seconds"`
	AvgAssistResolutionSeconds float64            `json:"avg_assist_resolution_seconds"`
	AnomalyCount               int32              `json:"anomaly_count"`
	ProjectedAt                pgtype.Timestamptz `json:"projected_at"`
}

type AnalyticsProjectorCheckpoint struct {
	ProjectorName      string             `json:"projector_name"`
	ProjectorVersion   int32              `json:"projector_version"`
	CursorOccurredAt   pgtype.Timestamptz `json:"cursor_occurred_at"`
	CursorEventID      uuid.NullUUID      `json:"cursor_event_id"`
	LagSeconds         float64            `json:"lag_seconds"`
	RebuildStatus      string             `json:"rebuild_status"`
	RebuildStartedAt   pgtype.Timestamptz `json:"rebuild_started_at"`
	RebuildCompletedAt pgtype.Timestamptz `json:"rebuild_completed_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type AnalyticsServicePeriodMetric struct {
	OrganisationID             uuid.UUID          `json:"organisation_id"`
	LocationID                 uuid.UUID          `json:"location_id"`
	ServicePeriodID            uuid.UUID          `json:"service_period_id"`
	MetricDate                 pgtype.Date        `json:"metric_date"`
	BucketStart                pgtype.Timestamptz `json:"bucket_start"`
	BucketEnd                  pgtype.Timestamptz `json:"bucket_end"`
	ActiveTableCount           int32              `json:"active_table_count"`
	OccupancySeconds           float64            `json:"occupancy_seconds"`
	UtilisationBasisSeconds    float64            `json:"utilisation_basis_seconds"`
	UtilisationRate            float64            `json:"utilisation_rate"`
	CompletedSessionCount      int32              `json:"completed_session_count"`
	TurnoverRate               float64            `json:"turnover_rate"`
	AvgSessionSeconds          float64            `json:"avg_session_seconds"`
	P50SessionSeconds          float64            `json:"p50_session_seconds"`
	P90SessionSeconds          float64            `json:"p90_session_seconds"`
	AssistRequestCount         int32              `json:"assist_request_count"`
	AvgAssistResponseSeconds   float64            `json:"avg_assist_response_seconds"`
	AvgAssistResolutionSeconds float64            `json:"avg_assist_resolution_seconds"`
	AnomalyCount               int32              `json:"anomaly_count"`
	ProjectedAt                pgtype.Timestamptz `json:"projected_at"`
}

type ApiIdempotencyRecord struct {
	CommandID      uuid.UUID          `json:"command_id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	LocationID     uuid.NullUUID      `json:"location_id"`
	CommandType    string             `json:"command_type"`
	PayloadHash    []byte             `json:"payload_hash"`
	ResponseStatus int32              `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type AssistRequest struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	LocationID     uuid.UUID          `json:"location_id"`
	TableID        uuid.UUID          `json:"table_id"`
	TableSessionID uuid.NullUUID      `json:"table_session_id"`
	Status         string             `json:"status"`
	RequestedAt    pgtype.Timestamptz `json:"requested_at"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	CancelledAt    pgtype.Timestamptz `json:"cancelled_at"`
	RequestedBy    pgtype.Text        `json:"requested_by"`
	AcknowledgedBy pgtype.Text        `json:"acknowledged_by"`
	ResolvedBy     pgtype.Text        `json:"resolved_by"`
	CancelledBy    pgtype.Text        `json:"cancelled_by"`
	Source         string             `json:"source"`
	Note           pgtype.Text        `json:"note"`
	Version        int32              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ActionKey      pgtype.Text        `json:"action_key"`
}

type AuditEvent struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.NullUUID      `json:"organisation_id"`
	LocationID     uuid.NullUUID      `json:"location_id"`
	ActorRef       string             `json:"actor_ref"`
	Action         string             `json:"action"`
	TargetType     string             `json:"target_type"`
	TargetID       string             `json:"target_id"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ConsumerEventRecord struct {
	ConsumerName   string             `json:"consumer_name"`
	EventID        uuid.UUID          `json:"event_id"`
	OutboxRecordID uuid.UUID          `json:"outbox_record_id"`
	Status         string             `json:"status"`
	FirstSeenAt    pgtype.Timestamptz `json:"first_seen_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	LastError      pgtype.Text        `json:"last_error"`
}

type Device struct {
	ID                       uuid.UUID          `json:"id"`
	OrganisationID           uuid.UUID          `json:"organisation_id"`
	LocationID               uuid.NullUUID      `json:"location_id"`
	UserProfileID            uuid.NullUUID      `json:"user_profile_id"`
	DeviceType               string             `json:"device_type"`
	Platform                 string             `json:"platform"`
	AppVersion               string             `json:"app_version"`
	TrustState               string             `json:"trust_state"`
	RegisteredAt             pgtype.Timestamptz `json:"registered_at"`
	LastSeenAt               pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt                pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	Name                     pgtype.Text        `json:"name"`
	Capabilities             []byte             `json:"capabilities"`
	Configuration            []byte             `json:"configuration"`
	AssignedAt               pgtype.Timestamptz `json:"assigned_at"`
	LastHeartbeatAt          pgtype.Timestamptz `json:"last_heartbeat_at"`
	HeartbeatIntervalSeconds int32              `json:"heartbeat_interval_seconds"`
}

type DeviceCredential struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	DeviceID       uuid.UUID          `json:"device_id"`
	LookupPrefix   string             `json:"lookup_prefix"`
	CredentialHash []byte             `json:"credential_hash"`
	IssuedAt       pgtype.Timestamptz `json:"issued_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DevicePairingCode struct {
	ID                      uuid.UUID          `json:"id"`
	OrganisationID          uuid.UUID          `json:"organisation_id"`
	LocationID              uuid.UUID          `json:"location_id"`
	CreatedBy               string             `json:"created_by"`
	DeviceType              string             `json:"device_type"`
	PairingCodeLookupPrefix string             `json:"pairing_code_lookup_prefix"`
	PairingCodeHash         []byte             `json:"pairing_code_hash"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt              pgtype.Timestamptz `json:"consumed_at"`
	ConsumedByDeviceID      uuid.NullUUID      `json:"consumed_by_device_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type ExternalIdentity struct {
	ID            uuid.UUID          `json:"id"`
	UserProfileID uuid.UUID          `json:"user_profile_id"`
	Issuer        string             `json:"issuer"`
	Subject       string             `json:"subject"`
	Email         pgtype.Text        `json:"email"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Floor struct {
	ID                 uuid.UUID          `json:"id"`
	OrganisationID     uuid.UUID          `json:"organisation_id"`
	LocationID         uuid.UUID          `json:"location_id"`
	Slug               string             `json:"slug"`
	Name               string             `json:"name"`
	SortOrder          int32              `json:"sort_order"`
	Canvas             []byte             `json:"canvas"`
	BackgroundAssetRef pgtype.Text        `json:"background_asset_ref"`
	IsActive           bool               `json:"is_active"`
	Version            int32              `json:"version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type GuestAbuseEvent struct {
	ID                uuid.UUID          `json:"id"`
	OrganisationID    uuid.NullUUID      `json:"organisation_id"`
	LocationID        uuid.NullUUID      `json:"location_id"`
	TableID           uuid.NullUUID      `json:"table_id"`
	TokenLookupPrefix string             `json:"token_lookup_prefix"`
	ActionKey         pgtype.Text        `json:"action_key"`
	IpHash            []byte             `json:"ip_hash"`
	Decision          string             `json:"decision"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type LegacyRestaurantMapping struct {
	LegacyRestaurantID string             `json:"legacy_restaurant_id"`
	OrganisationID     uuid.UUID          `json:"organisation_id"`
	LocationID         uuid.UUID          `json:"location_id"`
	MigratedAt         pgtype.Timestamptz `json:"migrated_at"`
}

type LegacyTableMapping struct {
	LegacyTableID  string             `json:"legacy_table_id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	LocationID     uuid.UUID          `json:"location_id"`
	TableID        uuid.UUID          `json:"table_id"`
	MigratedAt     pgtype.Timestamptz `json:"migrated_at"`
}

type Location struct {
	ID                 uuid.UUID          `json:"id"`
	OrganisationID     uuid.UUID          `json:"organisation_id"`
	Slug               string             `json:"slug"`
	Name               string             `json:"name"`
	Timezone           string             `json:"timezone"`
	Status             string             `json:"status"`
	LegacyRestaurantID pgtype.Text        `json:"legacy_restaurant_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	OperatingConfig    []byte             `json:"operating_config"`
	FeatureFlags       []byte             `json:"feature_flags"`
}

type LocationMembership struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	LocationID     uuid.UUID          `json:"location_id"`
	MemberRef      string             `json:"member_ref"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UserProfileID  uuid.NullUUID      `json:"user_profile_id"`
	DisabledAt     pgtype.Timestamptz `json:"disabled_at"`
}

type OperationalEvent struct {
	ID               uuid.UUID          `json:"id"`
	OrganisationID   uuid.UUID          `json:"organisation_id"`
	LocationID       uuid.UUID          `json:"location_id"`
	EventType        string             `json:"event_type"`
	AggregateType    string             `json:"aggregate_type"`
	AggregateID      uuid.UUID          `json:"aggregate_id"`
	AggregateVersion pgtype.Int4        `json:"aggregate_version"`
	ActorRef         string             `json:"actor_ref"`
	DeviceID         uuid.NullUUID      `json:"device_id"`
	CommandID        uuid.NullUUID      `json:"command_id"`
	Payload          []byte             `json:"payload"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	SchemaVersion    int32              `json:"schema_version"`
	EntityType       string             `json:"entity_type"`
	EntityID         uuid.UUID          `json:"entity_id"`
	EntityVersion    pgtype.Int4        `json:"entity_version"`
	CorrelationID    uuid.NullUUID      `json:"correlation_id"`
	EventData        []byte             `json:"event_data"`
}

type Organisation struct {
	ID                 uuid.UUID          `json:"id"`
	Slug               string             `json:"slug"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	LegacyRestaurantID pgtype.Text        `json:"legacy_restaurant_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type OrganisationMembership struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	MemberRef      string             `json:"member_ref"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UserProfileID  uuid.NullUUID      `json:"user_profile_id"`
	DisabledAt     pgtype.Timestamptz `json:"disabled_at"`
}

type OutboxRecord struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	LocationID     uuid.UUID          `json:"location_id"`
	EventID        uuid.UUID          `json:"event_id"`
	Topic          string             `json:"topic"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	AvailableAt    pgtype.Timestamptz `json:"available_at"`
	LockedAt       pgtype.Timestamptz `json:"locked_at"`
	LockedBy       pgtype.Text        `json:"locked_by"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Destination    string             `json:"destination"`
	LastError      pgtype.Text        `json:"last_error"`
}

type Permission struct {
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	Name        string             `json:"name"`
	Scope       string             `json:"scope"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleName       string             `json:"role_name"`
	PermissionName string             `json:"permission_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SchemaMigrationsMarker struct {
	ID        int32              `json:"id"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

type ServicePeriod struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	LocationID     uuid.UUID          `json:"location_id"`
	Name           string             `json:"name"`
	DaysOfWeek     []int16            `json:"days_of_week"`
	StartTime      pgtype.Time        `json:"start_time"`
	EndTime        pgtype.Time        `json:"end_time"`
	IsActive       bool               `json:"is_active"`
	Version        int32              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Table struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	LocationID     uuid.UUID          `json:"location_id"`
	FloorID        uuid.UUID          `json:"floor_id"`
	ZoneID         uuid.UUID          `json:"zone_id"`
	Label          string             `json:"label"`
	CapacityLabel  string             `json:"capacity_label"`
	Shape          string             `json:"shape"`
	Geometry       []byte             `json:"geometry"`
	IsActive       bool               `json:"is_active"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	Version        int32              `json:"version"`
	LegacyTableID  pgtype.Text        `json:"legacy_table_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TableOccupancy struct {
	TableID          uuid.UUID          `json:"table_id"`
	OrganisationID   uuid.UUID          `json:"organisation_id"`
	LocationID       uuid.UUID          `json:"location_id"`
	Status           string             `json:"status"`
	CurrentSessionID uuid.NullUUID      `json:"current_session_id"`
	Version          int32              `json:"version"`
	UpdatedBy        pgtype.Text        `json:"updated_by"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type TableQrCapability struct {
	ID                uuid.UUID          `json:"id"`
	OrganisationID    uuid.UUID          `json:"organisation_id"`
	LocationID        uuid.UUID          `json:"location_id"`
	TableID           uuid.UUID          `json:"table_id"`
	Token             string             `json:"token"`
	Label             pgtype.Text        `json:"label"`
	IssuedAt          pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	Version           int32              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	TokenLookupPrefix string             `json:"token_lookup_prefix"`
	TokenHash         []byte             `json:"token_hash"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
}

type TableSession struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	LocationID     uuid.UUID          `json:"location_id"`
	TableID        uuid.UUID          `json:"table_id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
	PartySize      pgtype.Int4        `json:"party_size"`
	OpenedBy       pgtype.Text        `json:"opened_by"`
	ClosedBy       pgtype.Text        `json:"closed_by"`
	Source         string             `json:"source"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type UserProfile struct {
	ID          uuid.UUID          `json:"id"`
	DisplayName string             `json:"display_name"`
	Email       pgtype.Text        `json:"email"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Zone struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	LocationID     uuid.UUID          `json:"location_id"`
	FloorID        uuid.UUID          `json:"floor_id"`
	Name           string             `json:"name"`
	SortOrder      int32              `json:"sort_order"`
	IsActive       bool               `json:"is_active"`
	Version        int32              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
