// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: operations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeAssistRequest = `-- name: AcknowledgeAssistRequest :one
UPDATE assist_requests
SET status = 'acknowledged',
    acknowledged_at = now(),
    acknowledged_by = $4,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND status = 'pending'
  AND version = $5
RETURNING id, organisation_id, location_id, table_id, table_session_id, status, requested_at, acknowledged_at, resolved_at, cancelled_at, requested_by, acknowledged_by, resolved_by, cancelled_by, source, note, version, created_at, updated_at, action_key
`

type AcknowledgeAssistRequestParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	AcknowledgedBy pgtype.Text `json:"acknowledged_by"`
	Version        int32       `json:"version"`
}

func (q *Queries) AcknowledgeAssistRequest(ctx context.Context, arg AcknowledgeAssistRequestParams) (AssistRequest, error) {
	row := q.db.QueryRow(ctx, acknowledgeAssistRequest,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.AcknowledgedBy,
		arg.Version,
	)
	var i AssistRequest
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.TableSessionID,
		&i.Status,
		&i.RequestedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.CancelledAt,
		&i.RequestedBy,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.CancelledBy,
		&i.Source,
		&i.Note,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActionKey,
	)
	return i, err
}

const cancelAssistRequest = `-- name: CancelAssistRequest :one
UPDATE assist_requests
SET status = 'cancelled',
    cancelled_at = now(),
    cancelled_by = $4,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND status IN ('pending', 'acknowledged')
  AND version = $5
RETURNING id, organisation_id, location_id, table_id, table_session_id, status, requested_at, acknowledged_at, resolved_at, cancelled_at, requested_by, acknowledged_by, resolved_by, cancelled_by, source, note, version, created_at, updated_at, action_key
`

type CancelAssistRequestParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	CancelledBy    pgtype.Text `json:"cancelled_by"`
	Version        int32       `json:"version"`
}

func (q *Queries) CancelAssistRequest(ctx context.Context, arg CancelAssistRequestParams) (AssistRequest, error) {
	row := q.db.QueryRow(ctx, cancelAssistRequest,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.CancelledBy,
		arg.Version,
	)
	var i AssistRequest
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.TableSessionID,
		&i.Status,
		&i.RequestedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.CancelledAt,
		&i.RequestedBy,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.CancelledBy,
		&i.Source,
		&i.Note,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActionKey,
	)
	return i, err
}

const cancelPendingGuestAssistRequest = `-- name: CancelPendingGuestAssistRequest :one
UPDATE assist_requests
SET status = 'cancelled',
    cancelled_at = now(),
    cancelled_by = $4,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND source = 'guest_qr'
  AND status = 'pending'
RETURNING id, organisation_id, location_id, table_id, table_session_id, status, requested_at, acknowledged_at, resolved_at, cancelled_at, requested_by, acknowledged_by, resolved_by, cancelled_by, source, note, version, created_at, updated_at, action_key
`

type CancelPendingGuestAssistRequestParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	CancelledBy    pgtype.Text `json:"cancelled_by"`
}

func (q *Queries) CancelPendingGuestAssistRequest(ctx context.Context, arg CancelPendingGuestAssistRequestParams) (AssistRequest, error) {
	row := q.db.QueryRow(ctx, cancelPendingGuestAssistRequest,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.CancelledBy,
	)
	var i AssistRequest
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.TableSessionID,
		&i.Status,
		&i.RequestedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.CancelledAt,
		&i.RequestedBy,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.CancelledBy,
		&i.Source,
		&i.Note,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActionKey,
	)
	return i, err
}

const closeTableSession = `-- name: CloseTableSession :one
UPDATE table_sessions
SET ended_at = now(),
    closed_by = $4,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND ended_at IS NULL
RETURNING id, organisation_id, location_id, table_id, started_at, ended_at, party_size, opened_by, closed_by, source, created_at, updated_at
`

type CloseTableSessionParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	ClosedBy       pgtype.Text `json:"closed_by"`
}

func (q *Queries) CloseTableSession(ctx context.Context, arg CloseTableSessionParams) (TableSession, error) {
	row := q.db.QueryRow(ctx, closeTableSession,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.ClosedBy,
	)
	var i TableSession
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.StartedAt,
		&i.EndedAt,
		&i.PartySize,
		&i.OpenedBy,
		&i.ClosedBy,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAssistRequest = `-- name: CreateAssistRequest :one
INSERT INTO assist_requests (
    organisation_id,
    location_id,
    table_id,
    table_session_id,
    requested_by,
    source,
    note,
    action_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organisation_id, location_id, table_id, table_session_id, status, requested_at, acknowledged_at, resolved_at, cancelled_at, requested_by, acknowledged_by, resolved_by, cancelled_by, source, note, version, created_at, updated_at, action_key
`

type CreateAssistRequestParams struct {
	OrganisationID uuid.UUID     `json:"organisation_id"`
	LocationID     uuid.UUID     `json:"location_id"`
	TableID        uuid.UUID     `json:"table_id"`
	TableSessionID uuid.NullUUID `json:"table_session_id"`
	RequestedBy    pgtype.Text   `json:"requested_by"`
	Source         string        `json:"source"`
	Note           pgtype.Text   `json:"note"`
	ActionKey      pgtype.Text   `json:"action_key"`
}

func (q *Queries) CreateAssistRequest(ctx context.Context, arg CreateAssistRequestParams) (AssistRequest, error) {
	row := q.db.QueryRow(ctx, createAssistRequest,
		arg.OrganisationID,
		arg.LocationID,
		arg.TableID,
		arg.TableSessionID,
		arg.RequestedBy,
		arg.Source,
		arg.Note,
		arg.ActionKey,
	)
	var i AssistRequest
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.TableSessionID,
		&i.Status,
		&i.RequestedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.CancelledAt,
		&i.RequestedBy,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.CancelledBy,
		&i.Source,
		&i.Note,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActionKey,
	)
	return i, err
}

const createTableSession = `-- name: CreateTableSession :one
INSERT INTO table_sessions (
    organisation_id,
    location_id,
    table_id,
    party_size,
    opened_by,
    source
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organisation_id, location_id, table_id, started_at, ended_at, party_size, opened_by, closed_by, source, created_at, updated_at
`

type CreateTableSessionParams struct {
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	TableID        uuid.UUID   `json:"table_id"`
	PartySize      pgtype.Int4 `json:"party_size"`
	OpenedBy       pgtype.Text `json:"opened_by"`
	Source         string      `json:"source"`
}

func (q *Queries) CreateTableSession(ctx context.Context, arg CreateTableSessionParams) (TableSession, error) {
	row := q.db.QueryRow(ctx, createTableSession,
		arg.OrganisationID,
		arg.LocationID,
		arg.TableID,
		arg.PartySize,
		arg.OpenedBy,
		arg.Source,
	)
	var i TableSession
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.StartedAt,
		&i.EndedAt,
		&i.PartySize,
		&i.OpenedBy,
		&i.ClosedBy,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveGuestAssistBySession = `-- name: GetActiveGuestAssistBySession :one
SELECT id, organisation_id, location_id, table_id, table_session_id, status, requested_at, acknowledged_at, resolved_at, cancelled_at, requested_by, acknowledged_by, resolved_by, cancelled_by, source, note, version, created_at, updated_at, action_key
FROM assist_requests
WHERE organisation_id = $1
  AND location_id = $2
  AND table_id = $3
  AND table_session_id = $4
  AND source = 'guest_qr'
  AND status IN ('pending', 'acknowledged')
ORDER BY requested_at DESC
LIMIT 1
`

type GetActiveGuestAssistBySessionParams struct {
	OrganisationID uuid.UUID     `json:"organisation_id"`
	LocationID     uuid.UUID     `json:"location_id"`
	TableID        uuid.UUID     `json:"table_id"`
	TableSessionID uuid.NullUUID `json:"table_session_id"`
}

func (q *Queries) GetActiveGuestAssistBySession(ctx context.Context, arg GetActiveGuestAssistBySessionParams) (AssistRequest, error) {
	row := q.db.QueryRow(ctx, getActiveGuestAssistBySession,
		arg.OrganisationID,
		arg.LocationID,
		arg.TableID,
		arg.TableSessionID,
	)
	var i AssistRequest
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.TableSessionID,
		&i.Status,
		&i.RequestedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.CancelledAt,
		&i.RequestedBy,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.CancelledBy,
		&i.Source,
		&i.Note,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActionKey,
	)
	return i, err
}

const getGuestAssistByID = `-- name: GetGuestAssistByID :one
SELECT id, organisation_id, location_id, table_id, table_session_id, status, requested_at, acknowledged_at, resolved_at, cancelled_at, requested_by, acknowledged_by, resolved_by, cancelled_by, source, note, version, created_at, updated_at, action_key
FROM assist_requests
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND table_id = $4
  AND source = 'guest_qr'
`

type GetGuestAssistByIDParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	TableID        uuid.UUID `json:"table_id"`
}

func (q *Queries) GetGuestAssistByID(ctx context.Context, arg GetGuestAssistByIDParams) (AssistRequest, error) {
	row := q.db.QueryRow(ctx, getGuestAssistByID,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.TableID,
	)
	var i AssistRequest
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.TableSessionID,
		&i.Status,
		&i.RequestedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.CancelledAt,
		&i.RequestedBy,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.CancelledBy,
		&i.Source,
		&i.Note,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActionKey,
	)
	return i, err
}

const getLatestTerminalGuestAssistByAction = `-- name: GetLatestTerminalGuestAssistByAction :one
SELECT id, organisation_id, location_id, table_id, table_session_id, status, requested_at, acknowledged_at, resolved_at, cancelled_at, requested_by, acknowledged_by, resolved_by, cancelled_by, source, note, version, created_at, updated_at, action_key
FROM assist_requests
WHERE organisation_id = $1
  AND location_id = $2
  AND table_id = $3
  AND table_session_id = $4
  AND action_key = $5
  AND source = 'guest_qr'
  AND status IN ('resolved', 'cancelled')
ORDER BY requested_at DESC
LIMIT 1
`

type GetLatestTerminalGuestAssistByActionParams struct {
	OrganisationID uuid.UUID     `json:"organisation_id"`
	LocationID     uuid.UUID     `json:"location_id"`
	TableID        uuid.UUID     `json:"table_id"`
	TableSessionID uuid.NullUUID `json:"table_session_id"`
	ActionKey      pgtype.Text   `json:"action_key"`
}

func (q *Queries) GetLatestTerminalGuestAssistByAction(ctx context.Context, arg GetLatestTerminalGuestAssistByActionParams) (AssistRequest, error) {
	row := q.db.QueryRow(ctx, getLatestTerminalGuestAssistByAction,
		arg.OrganisationID,
		arg.LocationID,
		arg.TableID,
		arg.TableSessionID,
		arg.ActionKey,
	)
	var i AssistRequest
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.TableSessionID,
		&i.Status,
		&i.RequestedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.CancelledAt,
		&i.RequestedBy,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.CancelledBy,
		&i.Source,
		&i.Note,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActionKey,
	)
	return i, err
}

const getPendingGuestAssistByAction = `-- name: GetPendingGuestAssistByAction :one
SELECT id, organisation_id, location_id, table_id, table_session_id, status, requested_at, acknowledged_at, resolved_at, cancelled_at, requested_by, acknowledged_by, resolved_by, cancelled_by, source, note, version, created_at, updated_at, action_key
FROM assist_requests
WHERE organisation_id = $1
  AND location_id = $2
  AND table_id = $3
  AND table_session_id = $4
  AND action_key = $5
  AND source = 'guest_qr'
  AND status = 'pending'
ORDER BY requested_at
LIMIT 1
FOR UPDATE
`

type GetPendingGuestAssistByActionParams struct {
	OrganisationID uuid.UUID     `json:"organisation_id"`
	LocationID     uuid.UUID     `json:"location_id"`
	TableID        uuid.UUID     `json:"table_id"`
	TableSessionID uuid.NullUUID `json:"table_session_id"`
	ActionKey      pgtype.Text   `json:"action_key"`
}

func (q *Queries) GetPendingGuestAssistByAction(ctx context.Context, arg GetPendingGuestAssistByActionParams) (AssistRequest, error) {
	row := q.db.QueryRow(ctx, getPendingGuestAssistByAction,
		arg.OrganisationID,
		arg.LocationID,
		arg.TableID,
		arg.TableSessionID,
		arg.ActionKey,
	)
	var i AssistRequest
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.TableSessionID,
		&i.Status,
		&i.RequestedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.CancelledAt,
		&i.RequestedBy,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.CancelledBy,
		&i.Source,
		&i.Note,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActionKey,
	)
	return i, err
}

const getTableState = `-- name: GetTableState :one
SELECT t.id, t.organisation_id, t.location_id, t.floor_id, t.zone_id, t.label, t.capacity_label, t.shape, t.geometry, t.is_active, t.deleted_at, t.version, t.legacy_table_id, t.created_at, t.updated_at, o.table_id, o.organisation_id, o.location_id, o.status, o.current_session_id, o.version, o.updated_by, o.updated_at, o.created_at
FROM tables t
JOIN table_occupancy o ON o.table_id = t.id
WHERE t.id = $1
  AND t.organisation_id = $2
  AND t.location_id = $3
  AND t.is_active
  AND t.deleted_at IS NULL
`

type GetTableStateParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

type GetTableStateRow struct {
	Table          Table          `json:"table"`
	TableOccupancy TableOccupancy `json:"table_occupancy"`
}

func (q *Queries) GetTableState(ctx context.Context, arg GetTableStateParams) (GetTableStateRow, error) {
	row := q.db.QueryRow(ctx, getTableState, arg.ID, arg.OrganisationID, arg.LocationID)
	var i GetTableStateRow
	err := row.Scan(
		&i.Table.ID,
		&i.Table.OrganisationID,
		&i.Table.LocationID,
		&i.Table.FloorID,
		&i.Table.ZoneID,
		&i.Table.Label,
		&i.Table.CapacityLabel,
		&i.Table.Shape,
		&i.Table.Geometry,
		&i.Table.IsActive,
		&i.Table.DeletedAt,
		&i.Table.Version,
		&i.Table.LegacyTableID,
		&i.Table.CreatedAt,
		&i.Table.UpdatedAt,
		&i.TableOccupancy.TableID,
		&i.TableOccupancy.OrganisationID,
		&i.TableOccupancy.LocationID,
		&i.TableOccupancy.Status,
		&i.TableOccupancy.CurrentSessionID,
		&i.TableOccupancy.Version,
		&i.TableOccupancy.UpdatedBy,
		&i.TableOccupancy.UpdatedAt,
		&i.TableOccupancy.CreatedAt,
	)
	return i, err
}

const listActiveAssistsByLocation = `-- name: ListActiveAssistsByLocation :many
SELECT id, organisation_id, location_id, table_id, table_session_id, status, requested_at, acknowledged_at, resolved_at, cancelled_at, requested_by, acknowledged_by, resolved_by, cancelled_by, source, note, version, created_at, updated_at, action_key
FROM assist_requests
WHERE organisation_id = $1
  AND location_id = $2
  AND status IN ('pending', 'acknowledged')
ORDER BY requested_at
`

type ListActiveAssistsByLocationParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

func (q *Queries) ListActiveAssistsByLocation(ctx context.Context, arg ListActiveAssistsByLocationParams) ([]AssistRequest, error) {
	rows, err := q.db.Query(ctx, listActiveAssistsByLocation, arg.OrganisationID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistRequest{}
	for rows.Next() {
		var i AssistRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.TableID,
			&i.TableSessionID,
			&i.Status,
			&i.RequestedAt,
			&i.AcknowledgedAt,
			&i.ResolvedAt,
			&i.CancelledAt,
			&i.RequestedBy,
			&i.AcknowledgedBy,
			&i.ResolvedBy,
			&i.CancelledBy,
			&i.Source,
			&i.Note,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActionKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAssistsByTable = `-- name: ListActiveAssistsByTable :many
SELECT id, organisation_id, location_id, table_id, table_session_id, status, requested_at, acknowledged_at, resolved_at, cancelled_at, requested_by, acknowledged_by, resolved_by, cancelled_by, source, note, version, created_at, updated_at, action_key
FROM assist_requests
WHERE organisation_id = $1
  AND location_id = $2
  AND table_id = $3
  AND status IN ('pending', 'acknowledged')
ORDER BY requested_at
`

type ListActiveAssistsByTableParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	TableID        uuid.UUID `json:"table_id"`
}

func (q *Queries) ListActiveAssistsByTable(ctx context.Context, arg ListActiveAssistsByTableParams) ([]AssistRequest, error) {
	rows, err := q.db.Query(ctx, listActiveAssistsByTable, arg.OrganisationID, arg.LocationID, arg.TableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistRequest{}
	for rows.Next() {
		var i AssistRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.TableID,
			&i.TableSessionID,
			&i.Status,
			&i.RequestedAt,
			&i.AcknowledgedAt,
			&i.ResolvedAt,
			&i.CancelledAt,
			&i.RequestedBy,
			&i.AcknowledgedBy,
			&i.ResolvedBy,
			&i.CancelledBy,
			&i.Source,
			&i.Note,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActionKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAssistRequest = `-- name: LockAssistRequest :one
SELECT id, organisation_id, location_id, table_id, table_session_id, status, requested_at, acknowledged_at, resolved_at, cancelled_at, requested_by, acknowledged_by, resolved_by, cancelled_by, source, note, version, created_at, updated_at, action_key
FROM assist_requests
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
FOR UPDATE
`

type LockAssistRequestParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

func (q *Queries) LockAssistRequest(ctx context.Context, arg LockAssistRequestParams) (AssistRequest, error) {
	row := q.db.QueryRow(ctx, lockAssistRequest, arg.ID, arg.OrganisationID, arg.LocationID)
	var i AssistRequest
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.TableSessionID,
		&i.Status,
		&i.RequestedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.CancelledAt,
		&i.RequestedBy,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.CancelledBy,
		&i.Source,
		&i.Note,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActionKey,
	)
	return i, err
}

const lockTableOccupancy = `-- name: LockTableOccupancy :one
SELECT o.table_id, o.organisation_id, o.location_id, o.status, o.current_session_id, o.version, o.updated_by, o.updated_at, o.created_at
FROM table_occupancy o
JOIN tables t ON t.id = o.table_id
WHERE o.table_id = $1
  AND o.organisation_id = $2
  AND o.location_id = $3
  AND t.is_active
  AND t.deleted_at IS NULL
FOR UPDATE OF o
`

type LockTableOccupancyParams struct {
	TableID        uuid.UUID `json:"table_id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

func (q *Queries) LockTableOccupancy(ctx context.Context, arg LockTableOccupancyParams) (TableOccupancy, error) {
	row := q.db.QueryRow(ctx, lockTableOccupancy, arg.TableID, arg.OrganisationID, arg.LocationID)
	var i TableOccupancy
	err := row.Scan(
		&i.TableID,
		&i.OrganisationID,
		&i.LocationID,
		&i.Status,
		&i.CurrentSessionID,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markTableAvailable = `-- name: MarkTableAvailable :one
UPDATE table_occupancy
SET status = 'available',
    current_session_id = NULL,
    version = version + 1,
    updated_by = $4,
    updated_at = now()
WHERE table_id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND status = 'occupied'
  AND version = $5
RETURNING table_id, organisation_id, location_id, status, current_session_id, version, updated_by, updated_at, created_at
`

type MarkTableAvailableParams struct {
	TableID        uuid.UUID   `json:"table_id"`
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	UpdatedBy      pgtype.Text `json:"updated_by"`
	Version        int32       `json:"version"`
}

func (q *Queries) MarkTableAvailable(ctx context.Context, arg MarkTableAvailableParams) (TableOccupancy, error) {
	row := q.db.QueryRow(ctx, markTableAvailable,
		arg.TableID,
		arg.OrganisationID,
		arg.LocationID,
		arg.UpdatedBy,
		arg.Version,
	)
	var i TableOccupancy
	err := row.Scan(
		&i.TableID,
		&i.OrganisationID,
		&i.LocationID,
		&i.Status,
		&i.CurrentSessionID,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markTableOccupied = `-- name: MarkTableOccupied :one
UPDATE table_occupancy
SET status = 'occupied',
    current_session_id = $4,
    version = version + 1,
    updated_by = $5,
    updated_at = now()
WHERE table_id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND status = 'available'
  AND version = $6
RETURNING table_id, organisation_id, location_id, status, current_session_id, version, updated_by, updated_at, created_at
`

type MarkTableOccupiedParams struct {
	TableID          uuid.UUID     `json:"table_id"`
	OrganisationID   uuid.UUID     `json:"organisation_id"`
	LocationID       uuid.UUID     `json:"location_id"`
	CurrentSessionID uuid.NullUUID `json:"current_session_id"`
	UpdatedBy        pgtype.Text   `json:"updated_by"`
	Version          int32         `json:"version"`
}

func (q *Queries) MarkTableOccupied(ctx context.Context, arg MarkTableOccupiedParams) (TableOccupancy, error) {
	row := q.db.QueryRow(ctx, markTableOccupied,
		arg.TableID,
		arg.OrganisationID,
		arg.LocationID,
		arg.CurrentSessionID,
		arg.UpdatedBy,
		arg.Version,
	)
	var i TableOccupancy
	err := row.Scan(
		&i.TableID,
		&i.OrganisationID,
		&i.LocationID,
		&i.Status,
		&i.CurrentSessionID,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const resolveAssistRequest = `-- name: ResolveAssistRequest :one
UPDATE assist_requests
SET status = 'resolved',
    resolved_at = now(),
    resolved_by = $4,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND status IN ('pending', 'acknowledged')
  AND version = $5
RETURNING id, organisation_id, location_id, table_id, table_session_id, status, requested_at, acknowledged_at, resolved_at, cancelled_at, requested_by, acknowledged_by, resolved_by, cancelled_by, source, note, version, created_at, updated_at, action_key
`

type ResolveAssistRequestParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganisationID uuid.UUID   `json:"organisation_id"`
	LocationID     uuid.UUID   `json:"location_id"`
	ResolvedBy     pgtype.Text `json:"resolved_by"`
	Version        int32       `json:"version"`
}

func (q *Queries) ResolveAssistRequest(ctx context.Context, arg ResolveAssistRequestParams) (AssistRequest, error) {
	row := q.db.QueryRow(ctx, resolveAssistRequest,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.ResolvedBy,
		arg.Version,
	)
	var i AssistRequest
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.TableSessionID,
		&i.Status,
		&i.RequestedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
		&i.CancelledAt,
		&i.RequestedBy,
		&i.AcknowledgedBy,
		&i.ResolvedBy,
		&i.CancelledBy,
		&i.Source,
		&i.Note,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActionKey,
	)
	return i, err
}
