// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: organisation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (organisation_id, slug, name, timezone, legacy_restaurant_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organisation_id, slug, name, timezone, status, legacy_restaurant_id, created_at, updated_at, operating_config, feature_flags
`

type CreateLocationParams struct {
	OrganisationID     uuid.UUID   `json:"organisation_id"`
	Slug               string      `json:"slug"`
	Name               string      `json:"name"`
	Timezone           string      `json:"timezone"`
	LegacyRestaurantID pgtype.Text `json:"legacy_restaurant_id"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.OrganisationID,
		arg.Slug,
		arg.Name,
		arg.Timezone,
		arg.LegacyRestaurantID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Slug,
		&i.Name,
		&i.Timezone,
		&i.Status,
		&i.LegacyRestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OperatingConfig,
		&i.FeatureFlags,
	)
	return i, err
}

const createLocationMembership = `-- name: CreateLocationMembership :one
INSERT INTO location_memberships (organisation_id, location_id, member_ref, role)
VALUES ($1, $2, $3, $4)
RETURNING id, organisation_id, location_id, member_ref, role, created_at, updated_at, user_profile_id, disabled_at
`

type CreateLocationMembershipParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	MemberRef      string    `json:"member_ref"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateLocationMembership(ctx context.Context, arg CreateLocationMembershipParams) (LocationMembership, error) {
	row := q.db.QueryRow(ctx, createLocationMembership,
		arg.OrganisationID,
		arg.LocationID,
		arg.MemberRef,
		arg.Role,
	)
	var i LocationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.MemberRef,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserProfileID,
		&i.DisabledAt,
	)
	return i, err
}

const createOrganisation = `-- name: CreateOrganisation :one
INSERT INTO organisations (slug, name, legacy_restaurant_id)
VALUES ($1, $2, $3)
RETURNING id, slug, name, status, legacy_restaurant_id, created_at, updated_at
`

type CreateOrganisationParams struct {
	Slug               string      `json:"slug"`
	Name               string      `json:"name"`
	LegacyRestaurantID pgtype.Text `json:"legacy_restaurant_id"`
}

func (q *Queries) CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (Organisation, error) {
	row := q.db.QueryRow(ctx, createOrganisation, arg.Slug, arg.Name, arg.LegacyRestaurantID)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.LegacyRestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganisationMembership = `-- name: CreateOrganisationMembership :one
INSERT INTO organisation_memberships (organisation_id, member_ref, role)
VALUES ($1, $2, $3)
RETURNING id, organisation_id, member_ref, role, created_at, updated_at, user_profile_id, disabled_at
`

type CreateOrganisationMembershipParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	MemberRef      string    `json:"member_ref"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateOrganisationMembership(ctx context.Context, arg CreateOrganisationMembershipParams) (OrganisationMembership, error) {
	row := q.db.QueryRow(ctx, createOrganisationMembership, arg.OrganisationID, arg.MemberRef, arg.Role)
	var i OrganisationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.MemberRef,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserProfileID,
		&i.DisabledAt,
	)
	return i, err
}

const getLocation = `-- name: GetLocation :one
SELECT id, organisation_id, slug, name, timezone, status, legacy_restaurant_id, created_at, updated_at, operating_config, feature_flags
FROM locations
WHERE id = $1 AND organisation_id = $2
`

type GetLocationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) GetLocation(ctx context.Context, arg GetLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, arg.ID, arg.OrganisationID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Slug,
		&i.Name,
		&i.Timezone,
		&i.Status,
		&i.LegacyRestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OperatingConfig,
		&i.FeatureFlags,
	)
	return i, err
}

const getOrganisation = `-- name: GetOrganisation :one
SELECT id, slug, name, status, legacy_restaurant_id, created_at, updated_at
FROM organisations
WHERE id = $1
`

func (q *Queries) GetOrganisation(ctx context.Context, id uuid.UUID) (Organisation, error) {
	row := q.db.QueryRow(ctx, getOrganisation, id)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.LegacyRestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocationsByOrganisation = `-- name: ListLocationsByOrganisation :many
SELECT id, organisation_id, slug, name, timezone, status, legacy_restaurant_id, created_at, updated_at, operating_config, feature_flags
FROM locations
WHERE organisation_id = $1
ORDER BY name, slug
`

func (q *Queries) ListLocationsByOrganisation(ctx context.Context, organisationID uuid.UUID) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocationsByOrganisation, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Slug,
			&i.Name,
			&i.Timezone,
			&i.Status,
			&i.LegacyRestaurantID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OperatingConfig,
			&i.FeatureFlags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET name = $3,
    timezone = $4,
    status = $5,
    operating_config = $6,
    feature_flags = $7,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
RETURNING id, organisation_id, slug, name, timezone, status, legacy_restaurant_id, created_at, updated_at, operating_config, feature_flags
`

type UpdateLocationParams struct {
	ID              uuid.UUID `json:"id"`
	OrganisationID  uuid.UUID `json:"organisation_id"`
	Name            string    `json:"name"`
	Timezone        string    `json:"timezone"`
	Status          string    `json:"status"`
	OperatingConfig []byte    `json:"operating_config"`
	FeatureFlags    []byte    `json:"feature_flags"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.OrganisationID,
		arg.Name,
		arg.Timezone,
		arg.Status,
		arg.OperatingConfig,
		arg.FeatureFlags,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.Slug,
		&i.Name,
		&i.Timezone,
		&i.Status,
		&i.LegacyRestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OperatingConfig,
		&i.FeatureFlags,
	)
	return i, err
}

const updateOrganisation = `-- name: UpdateOrganisation :one
UPDATE organisations
SET name = $3,
    status = $4,
    updated_at = now()
WHERE id = $1
  AND slug = $2
RETURNING id, slug, name, status, legacy_restaurant_id, created_at, updated_at
`

type UpdateOrganisationParams struct {
	ID     uuid.UUID `json:"id"`
	Slug   string    `json:"slug"`
	Name   string    `json:"name"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrganisation(ctx context.Context, arg UpdateOrganisationParams) (Organisation, error) {
	row := q.db.QueryRow(ctx, updateOrganisation,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Status,
	)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.LegacyRestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
