// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: platform.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformTenantDiagnostics = `-- name: GetPlatformTenantDiagnostics :one
WITH location_counts AS (
    SELECT
        count(*) FILTER (WHERE status = 'disabled') AS disabled_location_count
    FROM locations
    WHERE locations.organisation_id = $1
),
device_counts AS (
    SELECT
        count(*) FILTER (WHERE trust_state = 'trusted' AND last_heartbeat_at IS NULL) AS never_heartbeat_device_count,
        count(*) FILTER (
            WHERE trust_state = 'trusted'
              AND last_heartbeat_at IS NOT NULL
              AND last_heartbeat_at < now() - make_interval(secs => greatest(heartbeat_interval_seconds * 3, 180))
        ) AS stale_device_count,
        count(*) FILTER (WHERE trust_state = 'pending') AS pending_device_count,
        count(*) FILTER (WHERE trust_state = 'revoked') AS revoked_device_count
    FROM devices
    WHERE organisation_id = $1
),
integration_counts AS (
    SELECT
        count(*) AS integration_count,
        count(*) FILTER (WHERE status = 'connected') AS connected_integration_count,
        count(*) FILTER (WHERE status = 'degraded') AS degraded_integration_count,
        count(*) FILTER (WHERE status = 'disconnected') AS disconnected_integration_count,
        max(last_successful_sync_at)::timestamptz AS last_successful_sync_at
    FROM integration_connections
    WHERE organisation_id = $1
),
audit_counts AS (
    SELECT count(*) AS recent_platform_audit_count
    FROM audit_events
    WHERE organisation_id = $1
      AND action LIKE 'platform.%'
      AND created_at >= now() - interval '7 days'
),
checkpoint AS (
    SELECT lag_seconds, rebuild_status, updated_at
    FROM analytics_projector_checkpoints
    ORDER BY updated_at DESC
    LIMIT 1
)
SELECT
    COALESCE(location_counts.disabled_location_count, 0)::integer AS disabled_location_count,
    COALESCE(device_counts.never_heartbeat_device_count, 0)::integer AS never_heartbeat_device_count,
    COALESCE(device_counts.stale_device_count, 0)::integer AS stale_device_count,
    COALESCE(device_counts.pending_device_count, 0)::integer AS pending_device_count,
    COALESCE(device_counts.revoked_device_count, 0)::integer AS revoked_device_count,
    COALESCE(integration_counts.integration_count, 0)::integer AS integration_count,
    COALESCE(integration_counts.connected_integration_count, 0)::integer AS connected_integration_count,
    COALESCE(integration_counts.degraded_integration_count, 0)::integer AS degraded_integration_count,
    COALESCE(integration_counts.disconnected_integration_count, 0)::integer AS disconnected_integration_count,
    integration_counts.last_successful_sync_at::timestamptz AS last_successful_sync_at,
    COALESCE(audit_counts.recent_platform_audit_count, 0)::integer AS recent_platform_audit_count,
    checkpoint.lag_seconds AS analytics_lag_seconds,
    checkpoint.rebuild_status AS analytics_rebuild_status,
    checkpoint.updated_at AS analytics_checkpoint_updated_at
FROM location_counts, device_counts, integration_counts, audit_counts
LEFT JOIN checkpoint ON true
`

type GetPlatformTenantDiagnosticsRow struct {
	DisabledLocationCount        int32              `json:"disabled_location_count"`
	NeverHeartbeatDeviceCount    int32              `json:"never_heartbeat_device_count"`
	StaleDeviceCount             int32              `json:"stale_device_count"`
	PendingDeviceCount           int32              `json:"pending_device_count"`
	RevokedDeviceCount           int32              `json:"revoked_device_count"`
	IntegrationCount             int32              `json:"integration_count"`
	ConnectedIntegrationCount    int32              `json:"connected_integration_count"`
	DegradedIntegrationCount     int32              `json:"degraded_integration_count"`
	DisconnectedIntegrationCount int32              `json:"disconnected_integration_count"`
	LastSuccessfulSyncAt         pgtype.Timestamptz `json:"last_successful_sync_at"`
	RecentPlatformAuditCount     int32              `json:"recent_platform_audit_count"`
	AnalyticsLagSeconds          pgtype.Float8      `json:"analytics_lag_seconds"`
	AnalyticsRebuildStatus       pgtype.Text        `json:"analytics_rebuild_status"`
	AnalyticsCheckpointUpdatedAt pgtype.Timestamptz `json:"analytics_checkpoint_updated_at"`
}

func (q *Queries) GetPlatformTenantDiagnostics(ctx context.Context, organisationID uuid.UUID) (GetPlatformTenantDiagnosticsRow, error) {
	row := q.db.QueryRow(ctx, getPlatformTenantDiagnostics, organisationID)
	var i GetPlatformTenantDiagnosticsRow
	err := row.Scan(
		&i.DisabledLocationCount,
		&i.NeverHeartbeatDeviceCount,
		&i.StaleDeviceCount,
		&i.PendingDeviceCount,
		&i.RevokedDeviceCount,
		&i.IntegrationCount,
		&i.ConnectedIntegrationCount,
		&i.DegradedIntegrationCount,
		&i.DisconnectedIntegrationCount,
		&i.LastSuccessfulSyncAt,
		&i.RecentPlatformAuditCount,
		&i.AnalyticsLagSeconds,
		&i.AnalyticsRebuildStatus,
		&i.AnalyticsCheckpointUpdatedAt,
	)
	return i, err
}

const getPlatformTenantOverview = `-- name: GetPlatformTenantOverview :one
WITH tenant_locations AS (
    SELECT
        organisation_id,
        count(*) AS location_count,
        count(*) FILTER (WHERE status = 'active') AS active_location_count,
        count(*) FILTER (WHERE status = 'disabled') AS disabled_location_count
    FROM locations
    WHERE organisation_id = $1
    GROUP BY organisation_id
),
tenant_devices AS (
    SELECT
        organisation_id,
        count(*) AS device_count,
        count(*) FILTER (WHERE trust_state = 'trusted') AS trusted_device_count,
        count(*) FILTER (WHERE trust_state = 'pending') AS pending_device_count,
        count(*) FILTER (WHERE trust_state = 'revoked') AS revoked_device_count,
        max(last_seen_at)::timestamptz AS last_device_seen_at
    FROM devices
    WHERE organisation_id = $1
    GROUP BY organisation_id
),
tenant_activity AS (
    SELECT organisation_id, max(created_at) AS last_audit_at
    FROM audit_events
    WHERE organisation_id = $1
    GROUP BY organisation_id
)
SELECT
    organisations.id,
    organisations.slug,
    organisations.name,
    organisations.status,
    organisations.created_at,
    organisations.updated_at,
    COALESCE(tenant_locations.location_count, 0)::integer AS location_count,
    COALESCE(tenant_locations.active_location_count, 0)::integer AS active_location_count,
    COALESCE(tenant_locations.disabled_location_count, 0)::integer AS disabled_location_count,
    COALESCE(tenant_devices.device_count, 0)::integer AS device_count,
    COALESCE(tenant_devices.trusted_device_count, 0)::integer AS trusted_device_count,
    COALESCE(tenant_devices.pending_device_count, 0)::integer AS pending_device_count,
    COALESCE(tenant_devices.revoked_device_count, 0)::integer AS revoked_device_count,
    tenant_devices.last_device_seen_at::timestamptz AS last_device_seen_at,
    tenant_activity.last_audit_at::timestamptz AS last_audit_at
FROM organisations
LEFT JOIN tenant_locations ON tenant_locations.organisation_id = organisations.id
LEFT JOIN tenant_devices ON tenant_devices.organisation_id = organisations.id
LEFT JOIN tenant_activity ON tenant_activity.organisation_id = organisations.id
WHERE organisations.id = $1
`

type GetPlatformTenantOverviewRow struct {
	ID                    uuid.UUID          `json:"id"`
	Slug                  string             `json:"slug"`
	Name                  string             `json:"name"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	LocationCount         int32              `json:"location_count"`
	ActiveLocationCount   int32              `json:"active_location_count"`
	DisabledLocationCount int32              `json:"disabled_location_count"`
	DeviceCount           int32              `json:"device_count"`
	TrustedDeviceCount    int32              `json:"trusted_device_count"`
	PendingDeviceCount    int32              `json:"pending_device_count"`
	RevokedDeviceCount    int32              `json:"revoked_device_count"`
	LastDeviceSeenAt      pgtype.Timestamptz `json:"last_device_seen_at"`
	LastAuditAt           pgtype.Timestamptz `json:"last_audit_at"`
}

func (q *Queries) GetPlatformTenantOverview(ctx context.Context, id uuid.UUID) (GetPlatformTenantOverviewRow, error) {
	row := q.db.QueryRow(ctx, getPlatformTenantOverview, id)
	var i GetPlatformTenantOverviewRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationCount,
		&i.ActiveLocationCount,
		&i.DisabledLocationCount,
		&i.DeviceCount,
		&i.TrustedDeviceCount,
		&i.PendingDeviceCount,
		&i.RevokedDeviceCount,
		&i.LastDeviceSeenAt,
		&i.LastAuditAt,
	)
	return i, err
}

const listPlatformTenantDeviceCounts = `-- name: ListPlatformTenantDeviceCounts :many
SELECT
    trust_state,
    device_type,
    count(*)::integer AS device_count,
    max(last_seen_at)::timestamptz AS last_seen_at
FROM devices
WHERE organisation_id = $1
GROUP BY trust_state, device_type
ORDER BY trust_state, device_type
`

type ListPlatformTenantDeviceCountsRow struct {
	TrustState  string             `json:"trust_state"`
	DeviceType  string             `json:"device_type"`
	DeviceCount int32              `json:"device_count"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) ListPlatformTenantDeviceCounts(ctx context.Context, organisationID uuid.UUID) ([]ListPlatformTenantDeviceCountsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformTenantDeviceCounts, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformTenantDeviceCountsRow{}
	for rows.Next() {
		var i ListPlatformTenantDeviceCountsRow
		if err := rows.Scan(
			&i.TrustState,
			&i.DeviceType,
			&i.DeviceCount,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformTenantLocations = `-- name: ListPlatformTenantLocations :many
SELECT id, organisation_id, slug, name, timezone, status, created_at, updated_at
FROM locations
WHERE organisation_id = $1
ORDER BY status, name, slug
`

type ListPlatformTenantLocationsRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Timezone       string             `json:"timezone"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPlatformTenantLocations(ctx context.Context, organisationID uuid.UUID) ([]ListPlatformTenantLocationsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformTenantLocations, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformTenantLocationsRow{}
	for rows.Next() {
		var i ListPlatformTenantLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Slug,
			&i.Name,
			&i.Timezone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformTenantMembershipRoleCounts = `-- name: ListPlatformTenantMembershipRoleCounts :many
SELECT role, count(*)::integer AS member_count
FROM (
    SELECT organisation_memberships.role
    FROM organisation_memberships
    WHERE organisation_memberships.organisation_id = $1
      AND organisation_memberships.disabled_at IS NULL
    UNION ALL
    SELECT location_memberships.role
    FROM location_memberships
    WHERE location_memberships.organisation_id = $1
      AND location_memberships.disabled_at IS NULL
) memberships
GROUP BY role
ORDER BY role
`

type ListPlatformTenantMembershipRoleCountsRow struct {
	Role        string `json:"role"`
	MemberCount int32  `json:"member_count"`
}

func (q *Queries) ListPlatformTenantMembershipRoleCounts(ctx context.Context, organisationID uuid.UUID) ([]ListPlatformTenantMembershipRoleCountsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformTenantMembershipRoleCounts, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformTenantMembershipRoleCountsRow{}
	for rows.Next() {
		var i ListPlatformTenantMembershipRoleCountsRow
		if err := rows.Scan(&i.Role, &i.MemberCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlatformTenants = `-- name: SearchPlatformTenants :many
WITH tenant_locations AS (
    SELECT
        organisation_id,
        count(*) AS location_count,
        count(*) FILTER (WHERE status = 'active') AS active_location_count,
        count(*) FILTER (WHERE status = 'disabled') AS disabled_location_count
    FROM locations
    GROUP BY organisation_id
),
tenant_devices AS (
    SELECT
        organisation_id,
        count(*) AS device_count,
        count(*) FILTER (WHERE trust_state = 'trusted') AS trusted_device_count,
        max(last_seen_at)::timestamptz AS last_device_seen_at
    FROM devices
    GROUP BY organisation_id
),
tenant_activity AS (
    SELECT organisation_id, max(created_at) AS last_audit_at
    FROM audit_events
    WHERE organisation_id IS NOT NULL
    GROUP BY organisation_id
)
SELECT
    organisations.id,
    organisations.slug,
    organisations.name,
    organisations.status,
    organisations.created_at,
    organisations.updated_at,
    COALESCE(tenant_locations.location_count, 0)::integer AS location_count,
    COALESCE(tenant_locations.active_location_count, 0)::integer AS active_location_count,
    COALESCE(tenant_locations.disabled_location_count, 0)::integer AS disabled_location_count,
    COALESCE(tenant_devices.device_count, 0)::integer AS device_count,
    COALESCE(tenant_devices.trusted_device_count, 0)::integer AS trusted_device_count,
    tenant_devices.last_device_seen_at::timestamptz AS last_device_seen_at,
    tenant_activity.last_audit_at::timestamptz AS last_audit_at
FROM organisations
LEFT JOIN tenant_locations ON tenant_locations.organisation_id = organisations.id
LEFT JOIN tenant_devices ON tenant_devices.organisation_id = organisations.id
LEFT JOIN tenant_activity ON tenant_activity.organisation_id = organisations.id
WHERE
    $1::text = ''
    OR organisations.slug ILIKE '%' || $1::text || '%'
    OR organisations.name ILIKE '%' || $1::text || '%'
ORDER BY organisations.updated_at DESC, organisations.name, organisations.slug
LIMIT $2::integer
`

type SearchPlatformTenantsParams struct {
	Search      string `json:"search"`
	ResultLimit int32  `json:"result_limit"`
}

type SearchPlatformTenantsRow struct {
	ID                    uuid.UUID          `json:"id"`
	Slug                  string             `json:"slug"`
	Name                  string             `json:"name"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	LocationCount         int32              `json:"location_count"`
	ActiveLocationCount   int32              `json:"active_location_count"`
	DisabledLocationCount int32              `json:"disabled_location_count"`
	DeviceCount           int32              `json:"device_count"`
	TrustedDeviceCount    int32              `json:"trusted_device_count"`
	LastDeviceSeenAt      pgtype.Timestamptz `json:"last_device_seen_at"`
	LastAuditAt           pgtype.Timestamptz `json:"last_audit_at"`
}

func (q *Queries) SearchPlatformTenants(ctx context.Context, arg SearchPlatformTenantsParams) ([]SearchPlatformTenantsRow, error) {
	rows, err := q.db.Query(ctx, searchPlatformTenants, arg.Search, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlatformTenantsRow{}
	for rows.Next() {
		var i SearchPlatformTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationCount,
			&i.ActiveLocationCount,
			&i.DisabledLocationCount,
			&i.DeviceCount,
			&i.TrustedDeviceCount,
			&i.LastDeviceSeenAt,
			&i.LastAuditAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrganisationStatus = `-- name: SetOrganisationStatus :one
UPDATE organisations
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, slug, name, status, legacy_restaurant_id, created_at, updated_at
`

type SetOrganisationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetOrganisationStatus(ctx context.Context, arg SetOrganisationStatusParams) (Organisation, error) {
	row := q.db.QueryRow(ctx, setOrganisationStatus, arg.ID, arg.Status)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.LegacyRestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
