// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: platform.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumePlatformAdminGrant = `-- name: ConsumePlatformAdminGrant :one
UPDATE platform_admin_grants
SET consumed_at = now(),
    consumed_by_user_profile_id = $1
WHERE lower(btrim(email)) = lower(btrim($2))
  AND consumed_at IS NULL
  AND revoked_at IS NULL
RETURNING role, invited_by_actor_ref
`

type ConsumePlatformAdminGrantParams struct {
	ConsumedByUserProfileID uuid.NullUUID `json:"consumed_by_user_profile_id"`
	Btrim                   string        `json:"btrim"`
}

type ConsumePlatformAdminGrantRow struct {
	Role              string `json:"role"`
	InvitedByActorRef string `json:"invited_by_actor_ref"`
}

func (q *Queries) ConsumePlatformAdminGrant(ctx context.Context, arg ConsumePlatformAdminGrantParams) (ConsumePlatformAdminGrantRow, error) {
	row := q.db.QueryRow(ctx, consumePlatformAdminGrant, arg.ConsumedByUserProfileID, arg.Btrim)
	var i ConsumePlatformAdminGrantRow
	err := row.Scan(&i.Role, &i.InvitedByActorRef)
	return i, err
}

const countActivePlatformAdmins = `-- name: CountActivePlatformAdmins :one
SELECT count(*)::integer
FROM platform_memberships
WHERE role = 'platform_admin'
  AND disabled_at IS NULL
`

func (q *Queries) CountActivePlatformAdmins(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countActivePlatformAdmins)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createPlatformAdminGrant = `-- name: CreatePlatformAdminGrant :one
INSERT INTO platform_admin_grants (email, role, invited_by_actor_ref)
VALUES (lower(btrim($1)), $2, $3)
ON CONFLICT (lower(btrim(email))) WHERE consumed_at IS NULL AND revoked_at IS NULL
DO UPDATE SET
    role = EXCLUDED.role,
    invited_by_actor_ref = EXCLUDED.invited_by_actor_ref
RETURNING id, email, role, invited_by_actor_ref, created_at, consumed_at, consumed_by_user_profile_id, revoked_at, revoked_by_actor_ref
`

type CreatePlatformAdminGrantParams struct {
	Btrim             string `json:"btrim"`
	Role              string `json:"role"`
	InvitedByActorRef string `json:"invited_by_actor_ref"`
}

func (q *Queries) CreatePlatformAdminGrant(ctx context.Context, arg CreatePlatformAdminGrantParams) (PlatformAdminGrant, error) {
	row := q.db.QueryRow(ctx, createPlatformAdminGrant, arg.Btrim, arg.Role, arg.InvitedByActorRef)
	var i PlatformAdminGrant
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.InvitedByActorRef,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.ConsumedByUserProfileID,
		&i.RevokedAt,
		&i.RevokedByActorRef,
	)
	return i, err
}

const createPlatformMembership = `-- name: CreatePlatformMembership :one
INSERT INTO platform_memberships (user_profile_id, role, granted_by_actor_ref)
VALUES ($1, $2, $3)
ON CONFLICT (user_profile_id) WHERE disabled_at IS NULL DO UPDATE
SET role = EXCLUDED.role,
    updated_at = now()
RETURNING id, user_profile_id, role, granted_by_actor_ref, granted_at, disabled_at, disabled_by_actor_ref, created_at, updated_at
`

type CreatePlatformMembershipParams struct {
	UserProfileID     uuid.UUID `json:"user_profile_id"`
	Role              string    `json:"role"`
	GrantedByActorRef string    `json:"granted_by_actor_ref"`
}

func (q *Queries) CreatePlatformMembership(ctx context.Context, arg CreatePlatformMembershipParams) (PlatformMembership, error) {
	row := q.db.QueryRow(ctx, createPlatformMembership, arg.UserProfileID, arg.Role, arg.GrantedByActorRef)
	var i PlatformMembership
	err := row.Scan(
		&i.ID,
		&i.UserProfileID,
		&i.Role,
		&i.GrantedByActorRef,
		&i.GrantedAt,
		&i.DisabledAt,
		&i.DisabledByActorRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disablePlatformMembership = `-- name: DisablePlatformMembership :one
UPDATE platform_memberships
SET disabled_at = now(),
    disabled_by_actor_ref = $2,
    updated_at = now()
WHERE id = $1
  AND disabled_at IS NULL
RETURNING id, user_profile_id, role, granted_by_actor_ref, granted_at, disabled_at, disabled_by_actor_ref, created_at, updated_at
`

type DisablePlatformMembershipParams struct {
	ID                 uuid.UUID   `json:"id"`
	DisabledByActorRef pgtype.Text `json:"disabled_by_actor_ref"`
}

func (q *Queries) DisablePlatformMembership(ctx context.Context, arg DisablePlatformMembershipParams) (PlatformMembership, error) {
	row := q.db.QueryRow(ctx, disablePlatformMembership, arg.ID, arg.DisabledByActorRef)
	var i PlatformMembership
	err := row.Scan(
		&i.ID,
		&i.UserProfileID,
		&i.Role,
		&i.GrantedByActorRef,
		&i.GrantedAt,
		&i.DisabledAt,
		&i.DisabledByActorRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformMembership = `-- name: GetPlatformMembership :one
SELECT id, user_profile_id, role, granted_by_actor_ref, granted_at, disabled_at, disabled_by_actor_ref, created_at, updated_at
FROM platform_memberships
WHERE id = $1
`

func (q *Queries) GetPlatformMembership(ctx context.Context, id uuid.UUID) (PlatformMembership, error) {
	row := q.db.QueryRow(ctx, getPlatformMembership, id)
	var i PlatformMembership
	err := row.Scan(
		&i.ID,
		&i.UserProfileID,
		&i.Role,
		&i.GrantedByActorRef,
		&i.GrantedAt,
		&i.DisabledAt,
		&i.DisabledByActorRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformTenantDiagnostics = `-- name: GetPlatformTenantDiagnostics :one
WITH location_counts AS (
    SELECT
        count(*) FILTER (WHERE status = 'disabled') AS disabled_location_count
    FROM locations
    WHERE locations.organisation_id = $1
),
device_counts AS (
    SELECT
        count(*) FILTER (WHERE trust_state = 'trusted' AND last_heartbeat_at IS NULL) AS never_heartbeat_device_count,
        count(*) FILTER (
            WHERE trust_state = 'trusted'
              AND last_heartbeat_at IS NOT NULL
              AND last_heartbeat_at < now() - make_interval(secs => greatest(heartbeat_interval_seconds * 3, 180))
        ) AS stale_device_count,
        count(*) FILTER (WHERE trust_state = 'pending') AS pending_device_count,
        count(*) FILTER (WHERE trust_state = 'revoked') AS revoked_device_count
    FROM devices
    WHERE organisation_id = $1
),
integration_counts AS (
    SELECT
        count(*) AS integration_count,
        count(*) FILTER (WHERE status = 'connected') AS connected_integration_count,
        count(*) FILTER (WHERE status = 'degraded') AS degraded_integration_count,
        count(*) FILTER (WHERE status = 'disconnected') AS disconnected_integration_count,
        max(last_successful_sync_at)::timestamptz AS last_successful_sync_at
    FROM integration_connections
    WHERE organisation_id = $1
),
audit_counts AS (
    SELECT count(*) AS recent_platform_audit_count
    FROM audit_events
    WHERE organisation_id = $1
      AND action LIKE 'platform.%'
      AND created_at >= now() - interval '7 days'
),
checkpoint AS (
    SELECT lag_seconds, rebuild_status, updated_at
    FROM analytics_projector_checkpoints
    ORDER BY updated_at DESC
    LIMIT 1
)
SELECT
    COALESCE(location_counts.disabled_location_count, 0)::integer AS disabled_location_count,
    COALESCE(device_counts.never_heartbeat_device_count, 0)::integer AS never_heartbeat_device_count,
    COALESCE(device_counts.stale_device_count, 0)::integer AS stale_device_count,
    COALESCE(device_counts.pending_device_count, 0)::integer AS pending_device_count,
    COALESCE(device_counts.revoked_device_count, 0)::integer AS revoked_device_count,
    COALESCE(integration_counts.integration_count, 0)::integer AS integration_count,
    COALESCE(integration_counts.connected_integration_count, 0)::integer AS connected_integration_count,
    COALESCE(integration_counts.degraded_integration_count, 0)::integer AS degraded_integration_count,
    COALESCE(integration_counts.disconnected_integration_count, 0)::integer AS disconnected_integration_count,
    integration_counts.last_successful_sync_at::timestamptz AS last_successful_sync_at,
    COALESCE(audit_counts.recent_platform_audit_count, 0)::integer AS recent_platform_audit_count,
    checkpoint.lag_seconds AS analytics_lag_seconds,
    checkpoint.rebuild_status AS analytics_rebuild_status,
    checkpoint.updated_at AS analytics_checkpoint_updated_at
FROM location_counts, device_counts, integration_counts, audit_counts
LEFT JOIN checkpoint ON true
`

type GetPlatformTenantDiagnosticsRow struct {
	DisabledLocationCount        int32              `json:"disabled_location_count"`
	NeverHeartbeatDeviceCount    int32              `json:"never_heartbeat_device_count"`
	StaleDeviceCount             int32              `json:"stale_device_count"`
	PendingDeviceCount           int32              `json:"pending_device_count"`
	RevokedDeviceCount           int32              `json:"revoked_device_count"`
	IntegrationCount             int32              `json:"integration_count"`
	ConnectedIntegrationCount    int32              `json:"connected_integration_count"`
	DegradedIntegrationCount     int32              `json:"degraded_integration_count"`
	DisconnectedIntegrationCount int32              `json:"disconnected_integration_count"`
	LastSuccessfulSyncAt         pgtype.Timestamptz `json:"last_successful_sync_at"`
	RecentPlatformAuditCount     int32              `json:"recent_platform_audit_count"`
	AnalyticsLagSeconds          pgtype.Float8      `json:"analytics_lag_seconds"`
	AnalyticsRebuildStatus       pgtype.Text        `json:"analytics_rebuild_status"`
	AnalyticsCheckpointUpdatedAt pgtype.Timestamptz `json:"analytics_checkpoint_updated_at"`
}

func (q *Queries) GetPlatformTenantDiagnostics(ctx context.Context, organisationID uuid.UUID) (GetPlatformTenantDiagnosticsRow, error) {
	row := q.db.QueryRow(ctx, getPlatformTenantDiagnostics, organisationID)
	var i GetPlatformTenantDiagnosticsRow
	err := row.Scan(
		&i.DisabledLocationCount,
		&i.NeverHeartbeatDeviceCount,
		&i.StaleDeviceCount,
		&i.PendingDeviceCount,
		&i.RevokedDeviceCount,
		&i.IntegrationCount,
		&i.ConnectedIntegrationCount,
		&i.DegradedIntegrationCount,
		&i.DisconnectedIntegrationCount,
		&i.LastSuccessfulSyncAt,
		&i.RecentPlatformAuditCount,
		&i.AnalyticsLagSeconds,
		&i.AnalyticsRebuildStatus,
		&i.AnalyticsCheckpointUpdatedAt,
	)
	return i, err
}

const getPlatformTenantOverview = `-- name: GetPlatformTenantOverview :one
WITH tenant_locations AS (
    SELECT
        organisation_id,
        count(*) AS location_count,
        count(*) FILTER (WHERE status = 'active') AS active_location_count,
        count(*) FILTER (WHERE status = 'disabled') AS disabled_location_count
    FROM locations
    WHERE organisation_id = $1
    GROUP BY organisation_id
),
tenant_devices AS (
    SELECT
        organisation_id,
        count(*) AS device_count,
        count(*) FILTER (WHERE trust_state = 'trusted') AS trusted_device_count,
        count(*) FILTER (WHERE trust_state = 'pending') AS pending_device_count,
        count(*) FILTER (WHERE trust_state = 'revoked') AS revoked_device_count,
        max(last_seen_at)::timestamptz AS last_device_seen_at
    FROM devices
    WHERE organisation_id = $1
    GROUP BY organisation_id
),
tenant_activity AS (
    SELECT organisation_id, max(created_at) AS last_audit_at
    FROM audit_events
    WHERE organisation_id = $1
    GROUP BY organisation_id
)
SELECT
    organisations.id,
    organisations.slug,
    organisations.name,
    organisations.status,
    organisations.created_at,
    organisations.updated_at,
    COALESCE(tenant_locations.location_count, 0)::integer AS location_count,
    COALESCE(tenant_locations.active_location_count, 0)::integer AS active_location_count,
    COALESCE(tenant_locations.disabled_location_count, 0)::integer AS disabled_location_count,
    COALESCE(tenant_devices.device_count, 0)::integer AS device_count,
    COALESCE(tenant_devices.trusted_device_count, 0)::integer AS trusted_device_count,
    COALESCE(tenant_devices.pending_device_count, 0)::integer AS pending_device_count,
    COALESCE(tenant_devices.revoked_device_count, 0)::integer AS revoked_device_count,
    tenant_devices.last_device_seen_at::timestamptz AS last_device_seen_at,
    tenant_activity.last_audit_at::timestamptz AS last_audit_at
FROM organisations
LEFT JOIN tenant_locations ON tenant_locations.organisation_id = organisations.id
LEFT JOIN tenant_devices ON tenant_devices.organisation_id = organisations.id
LEFT JOIN tenant_activity ON tenant_activity.organisation_id = organisations.id
WHERE organisations.id = $1
`

type GetPlatformTenantOverviewRow struct {
	ID                    uuid.UUID          `json:"id"`
	Slug                  string             `json:"slug"`
	Name                  string             `json:"name"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	LocationCount         int32              `json:"location_count"`
	ActiveLocationCount   int32              `json:"active_location_count"`
	DisabledLocationCount int32              `json:"disabled_location_count"`
	DeviceCount           int32              `json:"device_count"`
	TrustedDeviceCount    int32              `json:"trusted_device_count"`
	PendingDeviceCount    int32              `json:"pending_device_count"`
	RevokedDeviceCount    int32              `json:"revoked_device_count"`
	LastDeviceSeenAt      pgtype.Timestamptz `json:"last_device_seen_at"`
	LastAuditAt           pgtype.Timestamptz `json:"last_audit_at"`
}

func (q *Queries) GetPlatformTenantOverview(ctx context.Context, id uuid.UUID) (GetPlatformTenantOverviewRow, error) {
	row := q.db.QueryRow(ctx, getPlatformTenantOverview, id)
	var i GetPlatformTenantOverviewRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationCount,
		&i.ActiveLocationCount,
		&i.DisabledLocationCount,
		&i.DeviceCount,
		&i.TrustedDeviceCount,
		&i.PendingDeviceCount,
		&i.RevokedDeviceCount,
		&i.LastDeviceSeenAt,
		&i.LastAuditAt,
	)
	return i, err
}

const listPlatformAdminGrants = `-- name: ListPlatformAdminGrants :many
SELECT id, email, role, invited_by_actor_ref, created_at, consumed_at, consumed_by_user_profile_id, revoked_at, revoked_by_actor_ref
FROM platform_admin_grants
ORDER BY revoked_at NULLS FIRST, consumed_at NULLS FIRST, created_at DESC
`

func (q *Queries) ListPlatformAdminGrants(ctx context.Context) ([]PlatformAdminGrant, error) {
	rows, err := q.db.Query(ctx, listPlatformAdminGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformAdminGrant{}
	for rows.Next() {
		var i PlatformAdminGrant
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.InvitedByActorRef,
			&i.CreatedAt,
			&i.ConsumedAt,
			&i.ConsumedByUserProfileID,
			&i.RevokedAt,
			&i.RevokedByActorRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformMemberships = `-- name: ListPlatformMemberships :many
SELECT
    pm.id,
    pm.user_profile_id,
    up.display_name,
    up.email,
    pm.role,
    pm.granted_by_actor_ref,
    pm.granted_at,
    pm.disabled_at,
    pm.disabled_by_actor_ref,
    pm.created_at,
    pm.updated_at
FROM platform_memberships pm
JOIN user_profiles up ON up.id = pm.user_profile_id
ORDER BY pm.disabled_at NULLS FIRST, pm.role, up.display_name, up.email
`

type ListPlatformMembershipsRow struct {
	ID                 uuid.UUID          `json:"id"`
	UserProfileID      uuid.UUID          `json:"user_profile_id"`
	DisplayName        string             `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Role               string             `json:"role"`
	GrantedByActorRef  string             `json:"granted_by_actor_ref"`
	GrantedAt          pgtype.Timestamptz `json:"granted_at"`
	DisabledAt         pgtype.Timestamptz `json:"disabled_at"`
	DisabledByActorRef pgtype.Text        `json:"disabled_by_actor_ref"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPlatformMemberships(ctx context.Context) ([]ListPlatformMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformMemberships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformMembershipsRow{}
	for rows.Next() {
		var i ListPlatformMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserProfileID,
			&i.DisplayName,
			&i.Email,
			&i.Role,
			&i.GrantedByActorRef,
			&i.GrantedAt,
			&i.DisabledAt,
			&i.DisabledByActorRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformTenantAudit = `-- name: ListPlatformTenantAudit :many
SELECT id, organisation_id, location_id, actor_ref, action, target_type, target_id, metadata, created_at
FROM audit_events
WHERE organisation_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListPlatformTenantAuditParams struct {
	OrganisationID uuid.NullUUID `json:"organisation_id"`
	Limit          int32         `json:"limit"`
}

func (q *Queries) ListPlatformTenantAudit(ctx context.Context, arg ListPlatformTenantAuditParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listPlatformTenantAudit, arg.OrganisationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.ActorRef,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformTenantDeviceCounts = `-- name: ListPlatformTenantDeviceCounts :many
SELECT
    trust_state,
    device_type,
    count(*)::integer AS device_count,
    max(last_seen_at)::timestamptz AS last_seen_at
FROM devices
WHERE organisation_id = $1
GROUP BY trust_state, device_type
ORDER BY trust_state, device_type
`

type ListPlatformTenantDeviceCountsRow struct {
	TrustState  string             `json:"trust_state"`
	DeviceType  string             `json:"device_type"`
	DeviceCount int32              `json:"device_count"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) ListPlatformTenantDeviceCounts(ctx context.Context, organisationID uuid.UUID) ([]ListPlatformTenantDeviceCountsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformTenantDeviceCounts, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformTenantDeviceCountsRow{}
	for rows.Next() {
		var i ListPlatformTenantDeviceCountsRow
		if err := rows.Scan(
			&i.TrustState,
			&i.DeviceType,
			&i.DeviceCount,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformTenantLocations = `-- name: ListPlatformTenantLocations :many
SELECT id, organisation_id, slug, name, timezone, status, created_at, updated_at
FROM locations
WHERE organisation_id = $1
ORDER BY status, name, slug
`

type ListPlatformTenantLocationsRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Timezone       string             `json:"timezone"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPlatformTenantLocations(ctx context.Context, organisationID uuid.UUID) ([]ListPlatformTenantLocationsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformTenantLocations, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformTenantLocationsRow{}
	for rows.Next() {
		var i ListPlatformTenantLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.Slug,
			&i.Name,
			&i.Timezone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformTenantMembershipRoleCounts = `-- name: ListPlatformTenantMembershipRoleCounts :many
SELECT role, count(*)::integer AS member_count
FROM (
    SELECT organisation_memberships.role
    FROM organisation_memberships
    WHERE organisation_memberships.organisation_id = $1
      AND organisation_memberships.disabled_at IS NULL
    UNION ALL
    SELECT location_memberships.role
    FROM location_memberships
    WHERE location_memberships.organisation_id = $1
      AND location_memberships.disabled_at IS NULL
) memberships
GROUP BY role
ORDER BY role
`

type ListPlatformTenantMembershipRoleCountsRow struct {
	Role        string `json:"role"`
	MemberCount int32  `json:"member_count"`
}

func (q *Queries) ListPlatformTenantMembershipRoleCounts(ctx context.Context, organisationID uuid.UUID) ([]ListPlatformTenantMembershipRoleCountsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformTenantMembershipRoleCounts, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformTenantMembershipRoleCountsRow{}
	for rows.Next() {
		var i ListPlatformTenantMembershipRoleCountsRow
		if err := rows.Scan(&i.Role, &i.MemberCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformTenantOwners = `-- name: ListPlatformTenantOwners :many
SELECT om.id, 'organisation' AS scope, om.organisation_id, NULL::uuid AS location_id, om.user_profile_id,
       up.display_name, up.email, om.member_ref, om.role, om.disabled_at
FROM organisation_memberships om
LEFT JOIN user_profiles up ON up.id = om.user_profile_id
WHERE om.organisation_id = $1
  AND om.role = 'organisation_owner'
  AND ($2::boolean OR om.disabled_at IS NULL)
ORDER BY om.disabled_at NULLS FIRST, up.display_name, om.member_ref
`

type ListPlatformTenantOwnersParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	Column2        bool      `json:"column_2"`
}

type ListPlatformTenantOwnersRow struct {
	ID             uuid.UUID          `json:"id"`
	Scope          string             `json:"scope"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	LocationID     uuid.NullUUID      `json:"location_id"`
	UserProfileID  uuid.NullUUID      `json:"user_profile_id"`
	DisplayName    pgtype.Text        `json:"display_name"`
	Email          pgtype.Text        `json:"email"`
	MemberRef      string             `json:"member_ref"`
	Role           string             `json:"role"`
	DisabledAt     pgtype.Timestamptz `json:"disabled_at"`
}

func (q *Queries) ListPlatformTenantOwners(ctx context.Context, arg ListPlatformTenantOwnersParams) ([]ListPlatformTenantOwnersRow, error) {
	rows, err := q.db.Query(ctx, listPlatformTenantOwners, arg.OrganisationID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformTenantOwnersRow{}
	for rows.Next() {
		var i ListPlatformTenantOwnersRow
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.OrganisationID,
			&i.LocationID,
			&i.UserProfileID,
			&i.DisplayName,
			&i.Email,
			&i.MemberRef,
			&i.Role,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivatePlatformMembership = `-- name: ReactivatePlatformMembership :one
UPDATE platform_memberships
SET disabled_at = NULL,
    disabled_by_actor_ref = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, user_profile_id, role, granted_by_actor_ref, granted_at, disabled_at, disabled_by_actor_ref, created_at, updated_at
`

func (q *Queries) ReactivatePlatformMembership(ctx context.Context, id uuid.UUID) (PlatformMembership, error) {
	row := q.db.QueryRow(ctx, reactivatePlatformMembership, id)
	var i PlatformMembership
	err := row.Scan(
		&i.ID,
		&i.UserProfileID,
		&i.Role,
		&i.GrantedByActorRef,
		&i.GrantedAt,
		&i.DisabledAt,
		&i.DisabledByActorRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokePlatformAdminGrant = `-- name: RevokePlatformAdminGrant :one
UPDATE platform_admin_grants
SET revoked_at = now(),
    revoked_by_actor_ref = $2
WHERE id = $1
  AND consumed_at IS NULL
  AND revoked_at IS NULL
RETURNING id, email, role, invited_by_actor_ref, created_at, consumed_at, consumed_by_user_profile_id, revoked_at, revoked_by_actor_ref
`

type RevokePlatformAdminGrantParams struct {
	ID                uuid.UUID   `json:"id"`
	RevokedByActorRef pgtype.Text `json:"revoked_by_actor_ref"`
}

func (q *Queries) RevokePlatformAdminGrant(ctx context.Context, arg RevokePlatformAdminGrantParams) (PlatformAdminGrant, error) {
	row := q.db.QueryRow(ctx, revokePlatformAdminGrant, arg.ID, arg.RevokedByActorRef)
	var i PlatformAdminGrant
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.InvitedByActorRef,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.ConsumedByUserProfileID,
		&i.RevokedAt,
		&i.RevokedByActorRef,
	)
	return i, err
}

const searchPlatformTenants = `-- name: SearchPlatformTenants :many
WITH tenant_locations AS (
    SELECT
        organisation_id,
        count(*) AS location_count,
        count(*) FILTER (WHERE status = 'active') AS active_location_count,
        count(*) FILTER (WHERE status = 'disabled') AS disabled_location_count
    FROM locations
    GROUP BY organisation_id
),
tenant_devices AS (
    SELECT
        organisation_id,
        count(*) AS device_count,
        count(*) FILTER (WHERE trust_state = 'trusted') AS trusted_device_count,
        max(last_seen_at)::timestamptz AS last_device_seen_at
    FROM devices
    GROUP BY organisation_id
),
tenant_activity AS (
    SELECT organisation_id, max(created_at) AS last_audit_at
    FROM audit_events
    WHERE organisation_id IS NOT NULL
    GROUP BY organisation_id
)
SELECT
    organisations.id,
    organisations.slug,
    organisations.name,
    organisations.status,
    organisations.created_at,
    organisations.updated_at,
    COALESCE(tenant_locations.location_count, 0)::integer AS location_count,
    COALESCE(tenant_locations.active_location_count, 0)::integer AS active_location_count,
    COALESCE(tenant_locations.disabled_location_count, 0)::integer AS disabled_location_count,
    COALESCE(tenant_devices.device_count, 0)::integer AS device_count,
    COALESCE(tenant_devices.trusted_device_count, 0)::integer AS trusted_device_count,
    tenant_devices.last_device_seen_at::timestamptz AS last_device_seen_at,
    tenant_activity.last_audit_at::timestamptz AS last_audit_at
FROM organisations
LEFT JOIN tenant_locations ON tenant_locations.organisation_id = organisations.id
LEFT JOIN tenant_devices ON tenant_devices.organisation_id = organisations.id
LEFT JOIN tenant_activity ON tenant_activity.organisation_id = organisations.id
WHERE
    $1::text = ''
    OR organisations.slug ILIKE '%' || $1::text || '%'
    OR organisations.name ILIKE '%' || $1::text || '%'
ORDER BY organisations.updated_at DESC, organisations.name, organisations.slug
LIMIT $2::integer
`

type SearchPlatformTenantsParams struct {
	Search      string `json:"search"`
	ResultLimit int32  `json:"result_limit"`
}

type SearchPlatformTenantsRow struct {
	ID                    uuid.UUID          `json:"id"`
	Slug                  string             `json:"slug"`
	Name                  string             `json:"name"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	LocationCount         int32              `json:"location_count"`
	ActiveLocationCount   int32              `json:"active_location_count"`
	DisabledLocationCount int32              `json:"disabled_location_count"`
	DeviceCount           int32              `json:"device_count"`
	TrustedDeviceCount    int32              `json:"trusted_device_count"`
	LastDeviceSeenAt      pgtype.Timestamptz `json:"last_device_seen_at"`
	LastAuditAt           pgtype.Timestamptz `json:"last_audit_at"`
}

func (q *Queries) SearchPlatformTenants(ctx context.Context, arg SearchPlatformTenantsParams) ([]SearchPlatformTenantsRow, error) {
	rows, err := q.db.Query(ctx, searchPlatformTenants, arg.Search, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlatformTenantsRow{}
	for rows.Next() {
		var i SearchPlatformTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationCount,
			&i.ActiveLocationCount,
			&i.DisabledLocationCount,
			&i.DeviceCount,
			&i.TrustedDeviceCount,
			&i.LastDeviceSeenAt,
			&i.LastAuditAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrganisationOnboarded = `-- name: SetOrganisationOnboarded :one
UPDATE organisations
SET onboarded_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, slug, name, status, legacy_restaurant_id, created_at, updated_at, onboarded_at
`

func (q *Queries) SetOrganisationOnboarded(ctx context.Context, id uuid.UUID) (Organisation, error) {
	row := q.db.QueryRow(ctx, setOrganisationOnboarded, id)
	var i Organisation
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.LegacyRestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardedAt,
	)
	return i, err
}

const setOrganisationStatus = `-- name: SetOrganisationStatus :one
UPDATE organisations
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, slug, name, status, legacy_restaurant_id, created_at, updated_at
`

type SetOrganisationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

type SetOrganisationStatusRow struct {
	ID                 uuid.UUID          `json:"id"`
	Slug               string             `json:"slug"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	LegacyRestaurantID pgtype.Text        `json:"legacy_restaurant_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetOrganisationStatus(ctx context.Context, arg SetOrganisationStatusParams) (SetOrganisationStatusRow, error) {
	row := q.db.QueryRow(ctx, setOrganisationStatus, arg.ID, arg.Status)
	var i SetOrganisationStatusRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.LegacyRestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
