// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: security.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const actorHasLocationPermission = `-- name: ActorHasLocationPermission :one
SELECT EXISTS (
    SELECT 1
    FROM location_memberships lm
    JOIN role_permissions rp ON rp.role_name = lm.role
    WHERE lm.organisation_id = $1
      AND lm.location_id = $2
      AND lm.member_ref = $3
      AND lm.disabled_at IS NULL
      AND rp.permission_name = $4
    UNION ALL
    SELECT 1
    FROM organisation_memberships om
    JOIN role_permissions rp ON rp.role_name = om.role
    WHERE om.organisation_id = $1
      AND om.member_ref = $3
      AND om.disabled_at IS NULL
      AND rp.permission_name = $4
) AS has_permission
`

type ActorHasLocationPermissionParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	MemberRef      string    `json:"member_ref"`
	PermissionName string    `json:"permission_name"`
}

func (q *Queries) ActorHasLocationPermission(ctx context.Context, arg ActorHasLocationPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, actorHasLocationPermission,
		arg.OrganisationID,
		arg.LocationID,
		arg.MemberRef,
		arg.PermissionName,
	)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const actorHasOrganisationPermission = `-- name: ActorHasOrganisationPermission :one
SELECT EXISTS (
    SELECT 1
    FROM organisation_memberships om
    JOIN role_permissions rp ON rp.role_name = om.role
    WHERE om.organisation_id = $1
      AND om.member_ref = $2
      AND om.disabled_at IS NULL
      AND rp.permission_name = $3
) AS has_permission
`

type ActorHasOrganisationPermissionParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	MemberRef      string    `json:"member_ref"`
	PermissionName string    `json:"permission_name"`
}

func (q *Queries) ActorHasOrganisationPermission(ctx context.Context, arg ActorHasOrganisationPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, actorHasOrganisationPermission, arg.OrganisationID, arg.MemberRef, arg.PermissionName)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const actorHasPlatformPermission = `-- name: ActorHasPlatformPermission :one
SELECT EXISTS (
    SELECT 1
    FROM platform_memberships pm
    JOIN role_permissions rp ON rp.role_name = pm.role
    WHERE pm.user_profile_id = $1
      AND pm.disabled_at IS NULL
      AND rp.permission_name = $2
) AS has_permission
`

type ActorHasPlatformPermissionParams struct {
	UserProfileID  uuid.UUID `json:"user_profile_id"`
	PermissionName string    `json:"permission_name"`
}

func (q *Queries) ActorHasPlatformPermission(ctx context.Context, arg ActorHasPlatformPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, actorHasPlatformPermission, arg.UserProfileID, arg.PermissionName)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const clearTenantContext = `-- name: ClearTenantContext :exec
SELECT set_config('seatd.platform_admin', 'false', true),
       set_config('seatd.current_organisation_id', '', true),
       set_config('seatd.current_location_id', '', true)
`

func (q *Queries) ClearTenantContext(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearTenantContext)
	return err
}

const consumeDevicePairingCode = `-- name: ConsumeDevicePairingCode :one
UPDATE device_pairing_codes
SET consumed_at = now(),
    consumed_by_device_id = $2,
    updated_at = now()
WHERE id = $1
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING id, organisation_id, location_id, created_by, device_type, pairing_code_lookup_prefix, pairing_code_hash, expires_at, consumed_at, consumed_by_device_id, created_at, updated_at
`

type ConsumeDevicePairingCodeParams struct {
	ID                 uuid.UUID     `json:"id"`
	ConsumedByDeviceID uuid.NullUUID `json:"consumed_by_device_id"`
}

func (q *Queries) ConsumeDevicePairingCode(ctx context.Context, arg ConsumeDevicePairingCodeParams) (DevicePairingCode, error) {
	row := q.db.QueryRow(ctx, consumeDevicePairingCode, arg.ID, arg.ConsumedByDeviceID)
	var i DevicePairingCode
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.CreatedBy,
		&i.DeviceType,
		&i.PairingCodeLookupPrefix,
		&i.PairingCodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedByDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeviceCredential = `-- name: CreateDeviceCredential :one
INSERT INTO device_credentials (organisation_id, device_id, lookup_prefix, credential_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organisation_id, device_id, lookup_prefix, credential_hash, issued_at, last_used_at, expires_at, revoked_at, created_at, updated_at
`

type CreateDeviceCredentialParams struct {
	OrganisationID uuid.UUID          `json:"organisation_id"`
	DeviceID       uuid.UUID          `json:"device_id"`
	LookupPrefix   string             `json:"lookup_prefix"`
	CredentialHash []byte             `json:"credential_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateDeviceCredential(ctx context.Context, arg CreateDeviceCredentialParams) (DeviceCredential, error) {
	row := q.db.QueryRow(ctx, createDeviceCredential,
		arg.OrganisationID,
		arg.DeviceID,
		arg.LookupPrefix,
		arg.CredentialHash,
		arg.ExpiresAt,
	)
	var i DeviceCredential
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.DeviceID,
		&i.LookupPrefix,
		&i.CredentialHash,
		&i.IssuedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDevicePairingCode = `-- name: CreateDevicePairingCode :one
INSERT INTO device_pairing_codes (
    organisation_id,
    location_id,
    created_by,
    device_type,
    pairing_code_lookup_prefix,
    pairing_code_hash,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organisation_id, location_id, created_by, device_type, pairing_code_lookup_prefix, pairing_code_hash, expires_at, consumed_at, consumed_by_device_id, created_at, updated_at
`

type CreateDevicePairingCodeParams struct {
	OrganisationID          uuid.UUID          `json:"organisation_id"`
	LocationID              uuid.UUID          `json:"location_id"`
	CreatedBy               string             `json:"created_by"`
	DeviceType              string             `json:"device_type"`
	PairingCodeLookupPrefix string             `json:"pairing_code_lookup_prefix"`
	PairingCodeHash         []byte             `json:"pairing_code_hash"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateDevicePairingCode(ctx context.Context, arg CreateDevicePairingCodeParams) (DevicePairingCode, error) {
	row := q.db.QueryRow(ctx, createDevicePairingCode,
		arg.OrganisationID,
		arg.LocationID,
		arg.CreatedBy,
		arg.DeviceType,
		arg.PairingCodeLookupPrefix,
		arg.PairingCodeHash,
		arg.ExpiresAt,
	)
	var i DevicePairingCode
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.CreatedBy,
		&i.DeviceType,
		&i.PairingCodeLookupPrefix,
		&i.PairingCodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedByDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTableQRCapabilityHashed = `-- name: CreateTableQRCapabilityHashed :one
INSERT INTO table_qr_capabilities (
    organisation_id,
    location_id,
    table_id,
    token,
    token_lookup_prefix,
    token_hash,
    label,
    expires_at
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::text,
    $4::text,
    $5::bytea,
    $6::text,
    $7::timestamptz
)
RETURNING id, organisation_id, location_id, table_id, token, label, issued_at, expires_at, revoked_at, version, created_at, updated_at, token_lookup_prefix, token_hash, last_used_at
`

type CreateTableQRCapabilityHashedParams struct {
	OrganisationID    uuid.UUID          `json:"organisation_id"`
	LocationID        uuid.UUID          `json:"location_id"`
	TableID           uuid.UUID          `json:"table_id"`
	TokenLookupPrefix string             `json:"token_lookup_prefix"`
	TokenHash         []byte             `json:"token_hash"`
	Label             string             `json:"label"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTableQRCapabilityHashed(ctx context.Context, arg CreateTableQRCapabilityHashedParams) (TableQrCapability, error) {
	row := q.db.QueryRow(ctx, createTableQRCapabilityHashed,
		arg.OrganisationID,
		arg.LocationID,
		arg.TableID,
		arg.TokenLookupPrefix,
		arg.TokenHash,
		arg.Label,
		arg.ExpiresAt,
	)
	var i TableQrCapability
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.Token,
		&i.Label,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenLookupPrefix,
		&i.TokenHash,
		&i.LastUsedAt,
	)
	return i, err
}

const createUserLocationMembership = `-- name: CreateUserLocationMembership :one
INSERT INTO location_memberships (organisation_id, location_id, user_profile_id, member_ref, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organisation_id, location_id, member_ref, role, created_at, updated_at, user_profile_id, disabled_at
`

type CreateUserLocationMembershipParams struct {
	OrganisationID uuid.UUID     `json:"organisation_id"`
	LocationID     uuid.UUID     `json:"location_id"`
	UserProfileID  uuid.NullUUID `json:"user_profile_id"`
	MemberRef      string        `json:"member_ref"`
	Role           string        `json:"role"`
}

func (q *Queries) CreateUserLocationMembership(ctx context.Context, arg CreateUserLocationMembershipParams) (LocationMembership, error) {
	row := q.db.QueryRow(ctx, createUserLocationMembership,
		arg.OrganisationID,
		arg.LocationID,
		arg.UserProfileID,
		arg.MemberRef,
		arg.Role,
	)
	var i LocationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.MemberRef,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserProfileID,
		&i.DisabledAt,
	)
	return i, err
}

const createUserOrganisationMembership = `-- name: CreateUserOrganisationMembership :one
INSERT INTO organisation_memberships (organisation_id, user_profile_id, member_ref, role)
VALUES ($1, $2, $3, $4)
RETURNING id, organisation_id, member_ref, role, created_at, updated_at, user_profile_id, disabled_at
`

type CreateUserOrganisationMembershipParams struct {
	OrganisationID uuid.UUID     `json:"organisation_id"`
	UserProfileID  uuid.NullUUID `json:"user_profile_id"`
	MemberRef      string        `json:"member_ref"`
	Role           string        `json:"role"`
}

func (q *Queries) CreateUserOrganisationMembership(ctx context.Context, arg CreateUserOrganisationMembershipParams) (OrganisationMembership, error) {
	row := q.db.QueryRow(ctx, createUserOrganisationMembership,
		arg.OrganisationID,
		arg.UserProfileID,
		arg.MemberRef,
		arg.Role,
	)
	var i OrganisationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.MemberRef,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserProfileID,
		&i.DisabledAt,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (display_name, email)
VALUES ($1, $2)
RETURNING id, display_name, email, status, created_at, updated_at
`

type CreateUserProfileParams struct {
	DisplayName string      `json:"display_name"`
	Email       pgtype.Text `json:"email"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile, arg.DisplayName, arg.Email)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebSession = `-- name: CreateWebSession :one
INSERT INTO web_sessions (
    user_profile_id,
    lookup_prefix,
    session_hash,
    expires_at,
    user_agent,
    ip_address,
    rotated_from_session_id
)
VALUES ($1, $2, $3, $4, $5, $6::inet, $7::uuid)
RETURNING id, user_profile_id, lookup_prefix, session_hash, issued_at, last_used_at, expires_at, revoked_at, rotated_from_session_id, user_agent, ip_address, created_at, updated_at
`

type CreateWebSessionParams struct {
	UserProfileID        uuid.UUID          `json:"user_profile_id"`
	LookupPrefix         string             `json:"lookup_prefix"`
	SessionHash          []byte             `json:"session_hash"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	UserAgent            pgtype.Text        `json:"user_agent"`
	IpAddress            *netip.Addr        `json:"ip_address"`
	RotatedFromSessionID uuid.NullUUID      `json:"rotated_from_session_id"`
}

func (q *Queries) CreateWebSession(ctx context.Context, arg CreateWebSessionParams) (WebSession, error) {
	row := q.db.QueryRow(ctx, createWebSession,
		arg.UserProfileID,
		arg.LookupPrefix,
		arg.SessionHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
		arg.RotatedFromSessionID,
	)
	var i WebSession
	err := row.Scan(
		&i.ID,
		&i.UserProfileID,
		&i.LookupPrefix,
		&i.SessionHash,
		&i.IssuedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RotatedFromSessionID,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTableQRCapabilityByHash = `-- name: GetActiveTableQRCapabilityByHash :one
SELECT table_qr_capabilities.id, table_qr_capabilities.organisation_id, table_qr_capabilities.location_id, table_qr_capabilities.table_id, table_qr_capabilities.token, table_qr_capabilities.label, table_qr_capabilities.issued_at, table_qr_capabilities.expires_at, table_qr_capabilities.revoked_at, table_qr_capabilities.version, table_qr_capabilities.created_at, table_qr_capabilities.updated_at, table_qr_capabilities.token_lookup_prefix, table_qr_capabilities.token_hash, table_qr_capabilities.last_used_at
FROM table_qr_capabilities
JOIN locations ON locations.id = table_qr_capabilities.location_id
    AND locations.organisation_id = table_qr_capabilities.organisation_id
JOIN tables ON tables.id = table_qr_capabilities.table_id
    AND tables.organisation_id = table_qr_capabilities.organisation_id
    AND tables.location_id = table_qr_capabilities.location_id
WHERE table_qr_capabilities.token_lookup_prefix = $1
  AND table_qr_capabilities.token_hash = $2
  AND table_qr_capabilities.revoked_at IS NULL
  AND (table_qr_capabilities.expires_at IS NULL OR table_qr_capabilities.expires_at > now())
  AND locations.status = 'active'
  AND tables.is_active
  AND tables.deleted_at IS NULL
`

type GetActiveTableQRCapabilityByHashParams struct {
	TokenLookupPrefix string `json:"token_lookup_prefix"`
	TokenHash         []byte `json:"token_hash"`
}

func (q *Queries) GetActiveTableQRCapabilityByHash(ctx context.Context, arg GetActiveTableQRCapabilityByHashParams) (TableQrCapability, error) {
	row := q.db.QueryRow(ctx, getActiveTableQRCapabilityByHash, arg.TokenLookupPrefix, arg.TokenHash)
	var i TableQrCapability
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.Token,
		&i.Label,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenLookupPrefix,
		&i.TokenHash,
		&i.LastUsedAt,
	)
	return i, err
}

const getActiveUserProfileByActorRef = `-- name: GetActiveUserProfileByActorRef :one
SELECT id, display_name, email, status, created_at, updated_at
FROM user_profiles
WHERE id = $1
  AND status = 'active'
`

func (q *Queries) GetActiveUserProfileByActorRef(ctx context.Context, id uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getActiveUserProfileByActorRef, id)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveUserProfileByEmail = `-- name: GetActiveUserProfileByEmail :one
SELECT id, display_name, email, status, created_at, updated_at
FROM user_profiles
WHERE lower(btrim(email)) = $1
  AND status = 'active'
`

func (q *Queries) GetActiveUserProfileByEmail(ctx context.Context, email pgtype.Text) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getActiveUserProfileByEmail, email)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, organisation_id, location_id, user_profile_id, device_type, platform, app_version, trust_state, registered_at, last_seen_at, revoked_at, created_at, updated_at, name, capabilities, configuration, assigned_at, last_heartbeat_at, heartbeat_interval_seconds
FROM devices
WHERE id = $1
  AND organisation_id = $2
`

type GetDeviceParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, arg.ID, arg.OrganisationID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.UserProfileID,
		&i.DeviceType,
		&i.Platform,
		&i.AppVersion,
		&i.TrustState,
		&i.RegisteredAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Capabilities,
		&i.Configuration,
		&i.AssignedAt,
		&i.LastHeartbeatAt,
		&i.HeartbeatIntervalSeconds,
	)
	return i, err
}

const getDeviceCredentialByPrefix = `-- name: GetDeviceCredentialByPrefix :one
SELECT device_credentials.id, device_credentials.organisation_id, device_credentials.device_id, device_credentials.lookup_prefix, device_credentials.credential_hash, device_credentials.issued_at, device_credentials.last_used_at, device_credentials.expires_at, device_credentials.revoked_at, device_credentials.created_at, device_credentials.updated_at, devices.id, devices.organisation_id, devices.location_id, devices.user_profile_id, devices.device_type, devices.platform, devices.app_version, devices.trust_state, devices.registered_at, devices.last_seen_at, devices.revoked_at, devices.created_at, devices.updated_at, devices.name, devices.capabilities, devices.configuration, devices.assigned_at, devices.last_heartbeat_at, devices.heartbeat_interval_seconds
FROM device_credentials
JOIN devices ON devices.id = device_credentials.device_id
WHERE device_credentials.lookup_prefix = $1
  AND device_credentials.revoked_at IS NULL
  AND (device_credentials.expires_at IS NULL OR device_credentials.expires_at > now())
  AND devices.trust_state = 'trusted'
  AND devices.revoked_at IS NULL
`

type GetDeviceCredentialByPrefixRow struct {
	DeviceCredential DeviceCredential `json:"device_credential"`
	Device           Device           `json:"device"`
}

func (q *Queries) GetDeviceCredentialByPrefix(ctx context.Context, lookupPrefix string) (GetDeviceCredentialByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getDeviceCredentialByPrefix, lookupPrefix)
	var i GetDeviceCredentialByPrefixRow
	err := row.Scan(
		&i.DeviceCredential.ID,
		&i.DeviceCredential.OrganisationID,
		&i.DeviceCredential.DeviceID,
		&i.DeviceCredential.LookupPrefix,
		&i.DeviceCredential.CredentialHash,
		&i.DeviceCredential.IssuedAt,
		&i.DeviceCredential.LastUsedAt,
		&i.DeviceCredential.ExpiresAt,
		&i.DeviceCredential.RevokedAt,
		&i.DeviceCredential.CreatedAt,
		&i.DeviceCredential.UpdatedAt,
		&i.Device.ID,
		&i.Device.OrganisationID,
		&i.Device.LocationID,
		&i.Device.UserProfileID,
		&i.Device.DeviceType,
		&i.Device.Platform,
		&i.Device.AppVersion,
		&i.Device.TrustState,
		&i.Device.RegisteredAt,
		&i.Device.LastSeenAt,
		&i.Device.RevokedAt,
		&i.Device.CreatedAt,
		&i.Device.UpdatedAt,
		&i.Device.Name,
		&i.Device.Capabilities,
		&i.Device.Configuration,
		&i.Device.AssignedAt,
		&i.Device.LastHeartbeatAt,
		&i.Device.HeartbeatIntervalSeconds,
	)
	return i, err
}

const getDevicePairingCodeByPrefix = `-- name: GetDevicePairingCodeByPrefix :one
SELECT device_pairing_codes.id, device_pairing_codes.organisation_id, device_pairing_codes.location_id, device_pairing_codes.created_by, device_pairing_codes.device_type, device_pairing_codes.pairing_code_lookup_prefix, device_pairing_codes.pairing_code_hash, device_pairing_codes.expires_at, device_pairing_codes.consumed_at, device_pairing_codes.consumed_by_device_id, device_pairing_codes.created_at, device_pairing_codes.updated_at
FROM device_pairing_codes
JOIN locations ON locations.id = device_pairing_codes.location_id
    AND locations.organisation_id = device_pairing_codes.organisation_id
WHERE device_pairing_codes.pairing_code_lookup_prefix = $1
  AND device_pairing_codes.consumed_at IS NULL
  AND device_pairing_codes.expires_at > now()
  AND locations.status = 'active'
`

func (q *Queries) GetDevicePairingCodeByPrefix(ctx context.Context, pairingCodeLookupPrefix string) (DevicePairingCode, error) {
	row := q.db.QueryRow(ctx, getDevicePairingCodeByPrefix, pairingCodeLookupPrefix)
	var i DevicePairingCode
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.CreatedBy,
		&i.DeviceType,
		&i.PairingCodeLookupPrefix,
		&i.PairingCodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedByDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT permission_name
FROM role_permissions
WHERE role_name = $1
ORDER BY permission_name
`

func (q *Queries) GetRolePermissions(ctx context.Context, roleName string) ([]string, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_name string
		if err := rows.Scan(&permission_name); err != nil {
			return nil, err
		}
		items = append(items, permission_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByExternalIdentity = `-- name: GetUserByExternalIdentity :one
SELECT user_profiles.id, user_profiles.display_name, user_profiles.email, user_profiles.status, user_profiles.created_at, user_profiles.updated_at, external_identities.id, external_identities.user_profile_id, external_identities.issuer, external_identities.subject, external_identities.email, external_identities.created_at, external_identities.updated_at
FROM external_identities
JOIN user_profiles ON user_profiles.id = external_identities.user_profile_id
WHERE external_identities.issuer = $1
  AND external_identities.subject = $2
  AND user_profiles.status = 'active'
`

type GetUserByExternalIdentityParams struct {
	Issuer  string `json:"issuer"`
	Subject string `json:"subject"`
}

type GetUserByExternalIdentityRow struct {
	UserProfile      UserProfile      `json:"user_profile"`
	ExternalIdentity ExternalIdentity `json:"external_identity"`
}

func (q *Queries) GetUserByExternalIdentity(ctx context.Context, arg GetUserByExternalIdentityParams) (GetUserByExternalIdentityRow, error) {
	row := q.db.QueryRow(ctx, getUserByExternalIdentity, arg.Issuer, arg.Subject)
	var i GetUserByExternalIdentityRow
	err := row.Scan(
		&i.UserProfile.ID,
		&i.UserProfile.DisplayName,
		&i.UserProfile.Email,
		&i.UserProfile.Status,
		&i.UserProfile.CreatedAt,
		&i.UserProfile.UpdatedAt,
		&i.ExternalIdentity.ID,
		&i.ExternalIdentity.UserProfileID,
		&i.ExternalIdentity.Issuer,
		&i.ExternalIdentity.Subject,
		&i.ExternalIdentity.Email,
		&i.ExternalIdentity.CreatedAt,
		&i.ExternalIdentity.UpdatedAt,
	)
	return i, err
}

const getWebSessionByPrefix = `-- name: GetWebSessionByPrefix :one
SELECT web_sessions.id, web_sessions.user_profile_id, web_sessions.lookup_prefix, web_sessions.session_hash, web_sessions.issued_at, web_sessions.last_used_at, web_sessions.expires_at, web_sessions.revoked_at, web_sessions.rotated_from_session_id, web_sessions.user_agent, web_sessions.ip_address, web_sessions.created_at, web_sessions.updated_at, user_profiles.id, user_profiles.display_name, user_profiles.email, user_profiles.status, user_profiles.created_at, user_profiles.updated_at
FROM web_sessions
JOIN user_profiles ON user_profiles.id = web_sessions.user_profile_id
WHERE web_sessions.lookup_prefix = $1
  AND web_sessions.revoked_at IS NULL
  AND web_sessions.expires_at > now()
  AND user_profiles.status = 'active'
`

type GetWebSessionByPrefixRow struct {
	WebSession  WebSession  `json:"web_session"`
	UserProfile UserProfile `json:"user_profile"`
}

func (q *Queries) GetWebSessionByPrefix(ctx context.Context, lookupPrefix string) (GetWebSessionByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getWebSessionByPrefix, lookupPrefix)
	var i GetWebSessionByPrefixRow
	err := row.Scan(
		&i.WebSession.ID,
		&i.WebSession.UserProfileID,
		&i.WebSession.LookupPrefix,
		&i.WebSession.SessionHash,
		&i.WebSession.IssuedAt,
		&i.WebSession.LastUsedAt,
		&i.WebSession.ExpiresAt,
		&i.WebSession.RevokedAt,
		&i.WebSession.RotatedFromSessionID,
		&i.WebSession.UserAgent,
		&i.WebSession.IpAddress,
		&i.WebSession.CreatedAt,
		&i.WebSession.UpdatedAt,
		&i.UserProfile.ID,
		&i.UserProfile.DisplayName,
		&i.UserProfile.Email,
		&i.UserProfile.Status,
		&i.UserProfile.CreatedAt,
		&i.UserProfile.UpdatedAt,
	)
	return i, err
}

const linkExternalIdentity = `-- name: LinkExternalIdentity :one
INSERT INTO external_identities (user_profile_id, issuer, subject, email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_profile_id, issuer, subject, email, created_at, updated_at
`

type LinkExternalIdentityParams struct {
	UserProfileID uuid.UUID   `json:"user_profile_id"`
	Issuer        string      `json:"issuer"`
	Subject       string      `json:"subject"`
	Email         pgtype.Text `json:"email"`
}

func (q *Queries) LinkExternalIdentity(ctx context.Context, arg LinkExternalIdentityParams) (ExternalIdentity, error) {
	row := q.db.QueryRow(ctx, linkExternalIdentity,
		arg.UserProfileID,
		arg.Issuer,
		arg.Subject,
		arg.Email,
	)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.UserProfileID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTableQRCapabilitiesByPrefix = `-- name: ListActiveTableQRCapabilitiesByPrefix :many
SELECT table_qr_capabilities.id, table_qr_capabilities.organisation_id, table_qr_capabilities.location_id, table_qr_capabilities.table_id, table_qr_capabilities.token, table_qr_capabilities.label, table_qr_capabilities.issued_at, table_qr_capabilities.expires_at, table_qr_capabilities.revoked_at, table_qr_capabilities.version, table_qr_capabilities.created_at, table_qr_capabilities.updated_at, table_qr_capabilities.token_lookup_prefix, table_qr_capabilities.token_hash, table_qr_capabilities.last_used_at
FROM table_qr_capabilities
JOIN locations ON locations.id = table_qr_capabilities.location_id
    AND locations.organisation_id = table_qr_capabilities.organisation_id
JOIN tables ON tables.id = table_qr_capabilities.table_id
    AND tables.organisation_id = table_qr_capabilities.organisation_id
    AND tables.location_id = table_qr_capabilities.location_id
WHERE table_qr_capabilities.token_lookup_prefix = $1
  AND table_qr_capabilities.revoked_at IS NULL
  AND (table_qr_capabilities.expires_at IS NULL OR table_qr_capabilities.expires_at > now())
  AND locations.status = 'active'
  AND tables.is_active
  AND tables.deleted_at IS NULL
ORDER BY table_qr_capabilities.issued_at DESC
`

func (q *Queries) ListActiveTableQRCapabilitiesByPrefix(ctx context.Context, tokenLookupPrefix string) ([]TableQrCapability, error) {
	rows, err := q.db.Query(ctx, listActiveTableQRCapabilitiesByPrefix, tokenLookupPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TableQrCapability{}
	for rows.Next() {
		var i TableQrCapability
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.TableID,
			&i.Token,
			&i.Label,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TokenLookupPrefix,
			&i.TokenHash,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByLocation = `-- name: ListDevicesByLocation :many
SELECT id, organisation_id, location_id, user_profile_id, device_type, platform, app_version, trust_state, registered_at, last_seen_at, revoked_at, created_at, updated_at, name, capabilities, configuration, assigned_at, last_heartbeat_at, heartbeat_interval_seconds
FROM devices
WHERE organisation_id = $1
  AND location_id = $2
ORDER BY registered_at DESC
`

type ListDevicesByLocationParams struct {
	OrganisationID uuid.UUID     `json:"organisation_id"`
	LocationID     uuid.NullUUID `json:"location_id"`
}

func (q *Queries) ListDevicesByLocation(ctx context.Context, arg ListDevicesByLocationParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByLocation, arg.OrganisationID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.UserProfileID,
			&i.DeviceType,
			&i.Platform,
			&i.AppVersion,
			&i.TrustState,
			&i.RegisteredAt,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Capabilities,
			&i.Configuration,
			&i.AssignedAt,
			&i.LastHeartbeatAt,
			&i.HeartbeatIntervalSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByOrganisation = `-- name: ListDevicesByOrganisation :many
SELECT id, organisation_id, location_id, user_profile_id, device_type, platform, app_version, trust_state, registered_at, last_seen_at, revoked_at, created_at, updated_at, name, capabilities, configuration, assigned_at, last_heartbeat_at, heartbeat_interval_seconds
FROM devices
WHERE organisation_id = $1
ORDER BY registered_at DESC
`

func (q *Queries) ListDevicesByOrganisation(ctx context.Context, organisationID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByOrganisation, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.UserProfileID,
			&i.DeviceType,
			&i.Platform,
			&i.AppVersion,
			&i.TrustState,
			&i.RegisteredAt,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Capabilities,
			&i.Configuration,
			&i.AssignedAt,
			&i.LastHeartbeatAt,
			&i.HeartbeatIntervalSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationMemberships = `-- name: ListLocationMemberships :many
SELECT id, organisation_id, location_id, member_ref, role, created_at, updated_at, user_profile_id, disabled_at
FROM location_memberships
WHERE organisation_id = $1
  AND location_id = $2
  AND disabled_at IS NULL
ORDER BY role, member_ref
`

type ListLocationMembershipsParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

func (q *Queries) ListLocationMemberships(ctx context.Context, arg ListLocationMembershipsParams) ([]LocationMembership, error) {
	rows, err := q.db.Query(ctx, listLocationMemberships, arg.OrganisationID, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LocationMembership{}
	for rows.Next() {
		var i LocationMembership
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.MemberRef,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserProfileID,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganisationMemberships = `-- name: ListOrganisationMemberships :many
SELECT id, organisation_id, member_ref, role, created_at, updated_at, user_profile_id, disabled_at
FROM organisation_memberships
WHERE organisation_id = $1
  AND disabled_at IS NULL
ORDER BY role, member_ref
`

func (q *Queries) ListOrganisationMemberships(ctx context.Context, organisationID uuid.UUID) ([]OrganisationMembership, error) {
	rows, err := q.db.Query(ctx, listOrganisationMemberships, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganisationMembership{}
	for rows.Next() {
		var i OrganisationMembership
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.MemberRef,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserProfileID,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTableQRCapabilitiesByTable = `-- name: ListTableQRCapabilitiesByTable :many
SELECT id, organisation_id, location_id, table_id, token, label, issued_at, expires_at, revoked_at, version, created_at, updated_at, token_lookup_prefix, token_hash, last_used_at
FROM table_qr_capabilities
WHERE organisation_id = $1
  AND location_id = $2
  AND table_id = $3
ORDER BY issued_at DESC
`

type ListTableQRCapabilitiesByTableParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	TableID        uuid.UUID `json:"table_id"`
}

func (q *Queries) ListTableQRCapabilitiesByTable(ctx context.Context, arg ListTableQRCapabilitiesByTableParams) ([]TableQrCapability, error) {
	rows, err := q.db.Query(ctx, listTableQRCapabilitiesByTable, arg.OrganisationID, arg.LocationID, arg.TableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TableQrCapability{}
	for rows.Next() {
		var i TableQrCapability
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.TableID,
			&i.Token,
			&i.Label,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TokenLookupPrefix,
			&i.TokenHash,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLocationMemberships = `-- name: ListUserLocationMemberships :many
SELECT id, organisation_id, location_id, member_ref, role, created_at, updated_at, user_profile_id, disabled_at
FROM location_memberships
WHERE user_profile_id = $1
  AND disabled_at IS NULL
ORDER BY role, member_ref
`

func (q *Queries) ListUserLocationMemberships(ctx context.Context, userProfileID uuid.NullUUID) ([]LocationMembership, error) {
	rows, err := q.db.Query(ctx, listUserLocationMemberships, userProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LocationMembership{}
	for rows.Next() {
		var i LocationMembership
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.LocationID,
			&i.MemberRef,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserProfileID,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrganisationMemberships = `-- name: ListUserOrganisationMemberships :many
SELECT id, organisation_id, member_ref, role, created_at, updated_at, user_profile_id, disabled_at
FROM organisation_memberships
WHERE user_profile_id = $1
  AND disabled_at IS NULL
ORDER BY role, member_ref
`

func (q *Queries) ListUserOrganisationMemberships(ctx context.Context, userProfileID uuid.NullUUID) ([]OrganisationMembership, error) {
	rows, err := q.db.Query(ctx, listUserOrganisationMemberships, userProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganisationMembership{}
	for rows.Next() {
		var i OrganisationMembership
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.MemberRef,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserProfileID,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPlatformMemberships = `-- name: ListUserPlatformMemberships :many
SELECT id, user_profile_id, role, granted_by_actor_ref, granted_at, disabled_at, disabled_by_actor_ref, created_at, updated_at
FROM platform_memberships
WHERE user_profile_id = $1
  AND disabled_at IS NULL
ORDER BY role
`

func (q *Queries) ListUserPlatformMemberships(ctx context.Context, userProfileID uuid.UUID) ([]PlatformMembership, error) {
	rows, err := q.db.Query(ctx, listUserPlatformMemberships, userProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformMembership{}
	for rows.Next() {
		var i PlatformMembership
		if err := rows.Scan(
			&i.ID,
			&i.UserProfileID,
			&i.Role,
			&i.GrantedByActorRef,
			&i.GrantedAt,
			&i.DisabledAt,
			&i.DisabledByActorRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeviceSeen = `-- name: MarkDeviceSeen :one
UPDATE devices
SET last_seen_at = now(),
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND trust_state = 'trusted'
  AND revoked_at IS NULL
RETURNING id, organisation_id, location_id, user_profile_id, device_type, platform, app_version, trust_state, registered_at, last_seen_at, revoked_at, created_at, updated_at, name, capabilities, configuration, assigned_at, last_heartbeat_at, heartbeat_interval_seconds
`

type MarkDeviceSeenParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) MarkDeviceSeen(ctx context.Context, arg MarkDeviceSeenParams) (Device, error) {
	row := q.db.QueryRow(ctx, markDeviceSeen, arg.ID, arg.OrganisationID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.UserProfileID,
		&i.DeviceType,
		&i.Platform,
		&i.AppVersion,
		&i.TrustState,
		&i.RegisteredAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Capabilities,
		&i.Configuration,
		&i.AssignedAt,
		&i.LastHeartbeatAt,
		&i.HeartbeatIntervalSeconds,
	)
	return i, err
}

const recordAuditEvent = `-- name: RecordAuditEvent :one
INSERT INTO audit_events (organisation_id, location_id, actor_ref, action, target_type, target_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organisation_id, location_id, actor_ref, action, target_type, target_id, metadata, created_at
`

type RecordAuditEventParams struct {
	OrganisationID uuid.NullUUID `json:"organisation_id"`
	LocationID     uuid.NullUUID `json:"location_id"`
	ActorRef       string        `json:"actor_ref"`
	Action         string        `json:"action"`
	TargetType     string        `json:"target_type"`
	TargetID       string        `json:"target_id"`
	Metadata       []byte        `json:"metadata"`
}

func (q *Queries) RecordAuditEvent(ctx context.Context, arg RecordAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, recordAuditEvent,
		arg.OrganisationID,
		arg.LocationID,
		arg.ActorRef,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.ActorRef,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const recordDeviceHeartbeat = `-- name: RecordDeviceHeartbeat :one
UPDATE devices
SET last_seen_at = now(),
    last_heartbeat_at = now(),
    app_version = $3,
    capabilities = $4,
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND trust_state = 'trusted'
  AND revoked_at IS NULL
RETURNING id, organisation_id, location_id, user_profile_id, device_type, platform, app_version, trust_state, registered_at, last_seen_at, revoked_at, created_at, updated_at, name, capabilities, configuration, assigned_at, last_heartbeat_at, heartbeat_interval_seconds
`

type RecordDeviceHeartbeatParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	AppVersion     string    `json:"app_version"`
	Capabilities   []byte    `json:"capabilities"`
}

func (q *Queries) RecordDeviceHeartbeat(ctx context.Context, arg RecordDeviceHeartbeatParams) (Device, error) {
	row := q.db.QueryRow(ctx, recordDeviceHeartbeat,
		arg.ID,
		arg.OrganisationID,
		arg.AppVersion,
		arg.Capabilities,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.UserProfileID,
		&i.DeviceType,
		&i.Platform,
		&i.AppVersion,
		&i.TrustState,
		&i.RegisteredAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Capabilities,
		&i.Configuration,
		&i.AssignedAt,
		&i.LastHeartbeatAt,
		&i.HeartbeatIntervalSeconds,
	)
	return i, err
}

const recordGuestAbuseEvent = `-- name: RecordGuestAbuseEvent :exec
INSERT INTO guest_abuse_events (
    organisation_id,
    location_id,
    table_id,
    token_lookup_prefix,
    action_key,
    ip_hash,
    decision
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type RecordGuestAbuseEventParams struct {
	OrganisationID    uuid.NullUUID `json:"organisation_id"`
	LocationID        uuid.NullUUID `json:"location_id"`
	TableID           uuid.NullUUID `json:"table_id"`
	TokenLookupPrefix string        `json:"token_lookup_prefix"`
	ActionKey         pgtype.Text   `json:"action_key"`
	IpHash            []byte        `json:"ip_hash"`
	Decision          string        `json:"decision"`
}

func (q *Queries) RecordGuestAbuseEvent(ctx context.Context, arg RecordGuestAbuseEventParams) error {
	_, err := q.db.Exec(ctx, recordGuestAbuseEvent,
		arg.OrganisationID,
		arg.LocationID,
		arg.TableID,
		arg.TokenLookupPrefix,
		arg.ActionKey,
		arg.IpHash,
		arg.Decision,
	)
	return err
}

const registerDevice = `-- name: RegisterDevice :one
INSERT INTO devices (
    organisation_id,
    location_id,
    user_profile_id,
    device_type,
    platform,
    app_version,
    name,
    capabilities,
    configuration,
    assigned_at,
    heartbeat_interval_seconds
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::text,
    $5::text,
    $6::text,
    $7::text,
    $8::jsonb,
    $9::jsonb,
    CASE WHEN $2::uuid IS NULL THEN NULL ELSE now() END,
    $10::integer
)
RETURNING id, organisation_id, location_id, user_profile_id, device_type, platform, app_version, trust_state, registered_at, last_seen_at, revoked_at, created_at, updated_at, name, capabilities, configuration, assigned_at, last_heartbeat_at, heartbeat_interval_seconds
`

type RegisterDeviceParams struct {
	OrganisationID           uuid.UUID     `json:"organisation_id"`
	LocationID               uuid.NullUUID `json:"location_id"`
	UserProfileID            uuid.NullUUID `json:"user_profile_id"`
	DeviceType               string        `json:"device_type"`
	Platform                 string        `json:"platform"`
	AppVersion               string        `json:"app_version"`
	Name                     pgtype.Text   `json:"name"`
	Capabilities             []byte        `json:"capabilities"`
	Configuration            []byte        `json:"configuration"`
	HeartbeatIntervalSeconds int32         `json:"heartbeat_interval_seconds"`
}

func (q *Queries) RegisterDevice(ctx context.Context, arg RegisterDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, registerDevice,
		arg.OrganisationID,
		arg.LocationID,
		arg.UserProfileID,
		arg.DeviceType,
		arg.Platform,
		arg.AppVersion,
		arg.Name,
		arg.Capabilities,
		arg.Configuration,
		arg.HeartbeatIntervalSeconds,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.UserProfileID,
		&i.DeviceType,
		&i.Platform,
		&i.AppVersion,
		&i.TrustState,
		&i.RegisteredAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Capabilities,
		&i.Configuration,
		&i.AssignedAt,
		&i.LastHeartbeatAt,
		&i.HeartbeatIntervalSeconds,
	)
	return i, err
}

const revokeDevice = `-- name: RevokeDevice :one
UPDATE devices
SET trust_state = 'revoked',
    revoked_at = now(),
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND revoked_at IS NULL
RETURNING id, organisation_id, location_id, user_profile_id, device_type, platform, app_version, trust_state, registered_at, last_seen_at, revoked_at, created_at, updated_at, name, capabilities, configuration, assigned_at, last_heartbeat_at, heartbeat_interval_seconds
`

type RevokeDeviceParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, revokeDevice, arg.ID, arg.OrganisationID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.UserProfileID,
		&i.DeviceType,
		&i.Platform,
		&i.AppVersion,
		&i.TrustState,
		&i.RegisteredAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Capabilities,
		&i.Configuration,
		&i.AssignedAt,
		&i.LastHeartbeatAt,
		&i.HeartbeatIntervalSeconds,
	)
	return i, err
}

const revokeDeviceCredentials = `-- name: RevokeDeviceCredentials :exec
UPDATE device_credentials
SET revoked_at = now(),
    updated_at = now()
WHERE organisation_id = $1
  AND device_id = $2
  AND revoked_at IS NULL
`

type RevokeDeviceCredentialsParams struct {
	OrganisationID uuid.UUID `json:"organisation_id"`
	DeviceID       uuid.UUID `json:"device_id"`
}

func (q *Queries) RevokeDeviceCredentials(ctx context.Context, arg RevokeDeviceCredentialsParams) error {
	_, err := q.db.Exec(ctx, revokeDeviceCredentials, arg.OrganisationID, arg.DeviceID)
	return err
}

const revokeTableQRCapability = `-- name: RevokeTableQRCapability :one
UPDATE table_qr_capabilities
SET revoked_at = now(),
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND revoked_at IS NULL
RETURNING id, organisation_id, location_id, table_id, token, label, issued_at, expires_at, revoked_at, version, created_at, updated_at, token_lookup_prefix, token_hash, last_used_at
`

type RevokeTableQRCapabilityParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
}

func (q *Queries) RevokeTableQRCapability(ctx context.Context, arg RevokeTableQRCapabilityParams) (TableQrCapability, error) {
	row := q.db.QueryRow(ctx, revokeTableQRCapability, arg.ID, arg.OrganisationID, arg.LocationID)
	var i TableQrCapability
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.Token,
		&i.Label,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenLookupPrefix,
		&i.TokenHash,
		&i.LastUsedAt,
	)
	return i, err
}

const revokeWebSession = `-- name: RevokeWebSession :exec
UPDATE web_sessions
SET revoked_at = COALESCE(revoked_at, now()),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) RevokeWebSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeWebSession, id)
	return err
}

const rotateTableQRCapability = `-- name: RotateTableQRCapability :one
UPDATE table_qr_capabilities
SET revoked_at = COALESCE(revoked_at, now()),
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND location_id = $3
  AND table_id = $4
RETURNING id, organisation_id, location_id, table_id, token, label, issued_at, expires_at, revoked_at, version, created_at, updated_at, token_lookup_prefix, token_hash, last_used_at
`

type RotateTableQRCapabilityParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
	LocationID     uuid.UUID `json:"location_id"`
	TableID        uuid.UUID `json:"table_id"`
}

func (q *Queries) RotateTableQRCapability(ctx context.Context, arg RotateTableQRCapabilityParams) (TableQrCapability, error) {
	row := q.db.QueryRow(ctx, rotateTableQRCapability,
		arg.ID,
		arg.OrganisationID,
		arg.LocationID,
		arg.TableID,
	)
	var i TableQrCapability
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.TableID,
		&i.Token,
		&i.Label,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TokenLookupPrefix,
		&i.TokenHash,
		&i.LastUsedAt,
	)
	return i, err
}

const setPlatformAdminContext = `-- name: SetPlatformAdminContext :exec
SELECT set_config('seatd.platform_admin', 'true', true)
`

func (q *Queries) SetPlatformAdminContext(ctx context.Context) error {
	_, err := q.db.Exec(ctx, setPlatformAdminContext)
	return err
}

const setTenantContext = `-- name: SetTenantContext :exec
SELECT set_config('seatd.platform_admin', 'false', true),
       set_config('seatd.current_organisation_id', $1::text, true),
       set_config('seatd.current_location_id', COALESCE($2::text, ''), true)
`

type SetTenantContextParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) SetTenantContext(ctx context.Context, arg SetTenantContextParams) error {
	_, err := q.db.Exec(ctx, setTenantContext, arg.Column1, arg.Column2)
	return err
}

const touchDeviceCredential = `-- name: TouchDeviceCredential :exec
UPDATE device_credentials
SET last_used_at = now(),
    updated_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) TouchDeviceCredential(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchDeviceCredential, id)
	return err
}

const touchTableQRCapability = `-- name: TouchTableQRCapability :exec
UPDATE table_qr_capabilities
SET last_used_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchTableQRCapability(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchTableQRCapability, id)
	return err
}

const touchWebSession = `-- name: TouchWebSession :exec
UPDATE web_sessions
SET last_used_at = now(),
    updated_at = now()
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) TouchWebSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchWebSession, id)
	return err
}

const trustDevice = `-- name: TrustDevice :one
UPDATE devices
SET trust_state = 'trusted',
    updated_at = now()
WHERE id = $1
  AND organisation_id = $2
  AND revoked_at IS NULL
RETURNING id, organisation_id, location_id, user_profile_id, device_type, platform, app_version, trust_state, registered_at, last_seen_at, revoked_at, created_at, updated_at, name, capabilities, configuration, assigned_at, last_heartbeat_at, heartbeat_interval_seconds
`

type TrustDeviceParams struct {
	ID             uuid.UUID `json:"id"`
	OrganisationID uuid.UUID `json:"organisation_id"`
}

func (q *Queries) TrustDevice(ctx context.Context, arg TrustDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, trustDevice, arg.ID, arg.OrganisationID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.LocationID,
		&i.UserProfileID,
		&i.DeviceType,
		&i.Platform,
		&i.AppVersion,
		&i.TrustState,
		&i.RegisteredAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Capabilities,
		&i.Configuration,
		&i.AssignedAt,
		&i.LastHeartbeatAt,
		&i.HeartbeatIntervalSeconds,
	)
	return i, err
}

const userHasLocationPermission = `-- name: UserHasLocationPermission :one
SELECT EXISTS (
    SELECT 1
    FROM location_memberships lm
    JOIN role_permissions rp ON rp.role_name = lm.role
    WHERE lm.organisation_id = $1
      AND lm.location_id = $2
      AND lm.user_profile_id = $3
      AND lm.disabled_at IS NULL
      AND rp.permission_name = $4
    UNION ALL
    SELECT 1
    FROM organisation_memberships om
    JOIN role_permissions rp ON rp.role_name = om.role
    WHERE om.organisation_id = $1
      AND om.user_profile_id = $3
      AND om.disabled_at IS NULL
      AND rp.permission_name = $4
) AS has_permission
`

type UserHasLocationPermissionParams struct {
	OrganisationID uuid.UUID     `json:"organisation_id"`
	LocationID     uuid.UUID     `json:"location_id"`
	UserProfileID  uuid.NullUUID `json:"user_profile_id"`
	PermissionName string        `json:"permission_name"`
}

func (q *Queries) UserHasLocationPermission(ctx context.Context, arg UserHasLocationPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasLocationPermission,
		arg.OrganisationID,
		arg.LocationID,
		arg.UserProfileID,
		arg.PermissionName,
	)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const userHasOrganisationPermission = `-- name: UserHasOrganisationPermission :one
SELECT EXISTS (
    SELECT 1
    FROM organisation_memberships om
    JOIN role_permissions rp ON rp.role_name = om.role
    WHERE om.organisation_id = $1
      AND om.user_profile_id = $2
      AND om.disabled_at IS NULL
      AND rp.permission_name = $3
) AS has_permission
`

type UserHasOrganisationPermissionParams struct {
	OrganisationID uuid.UUID     `json:"organisation_id"`
	UserProfileID  uuid.NullUUID `json:"user_profile_id"`
	PermissionName string        `json:"permission_name"`
}

func (q *Queries) UserHasOrganisationPermission(ctx context.Context, arg UserHasOrganisationPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasOrganisationPermission, arg.OrganisationID, arg.UserProfileID, arg.PermissionName)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}
